### ISSUE TITLE
[Bug] Many warnings being generated to HA log due to unverified SSL certificate

### ISSUE THREAD

**Issue by arkomax** [tomaae/homeassistant-truenas#100]
## Describe the issue

On the initial setup screen, after inputting the name, host and api key, the only way I can add the integration to HA, is if i select "use SSL" but deselect "verify SSL cert". Having the "verify SSL cert" ticked results in an error "No response from host" upon submitting, and the integration wouldn't be added.

I presume this is because my TrueNAS is configured with a self-signed cert and it's own CA?

The problem is, with the above setup, the HA log is bombarded with the following warning:

```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/truenas/truenas_api.py:70
Integration: TrueNAS (documentation, issues)
First occurred: 17:02:39 (614 occurrences)
Last logged: 17:26:36

/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.100'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(
```

## Possible resolution

According to this [StackOverflow post](https://stackoverflow.com/questions/68445066/how-to-fix-insecurerequestwarning-unverified-https-request-is-being-made-to-hos) if you set "verify=None" instead of "verify=False" in the saved parameters of the components settings, the above warnings could be resolved?

## Software versions

 - Home Assistant version: HA 2023.8.4
 - TrueNAS integration version: 1.2.3
 - TrueNAS version: 13.0-U5.3

**Comment by tomaae** [comment]
```
    :param verify: (optional) Either a boolean, in which case it controls whether we verify
            the server's TLS certificate, or a string, in which case it must be a path
            to a CA bundle to use. Defaults to ``True``.
```
It is actually bool|str
Value None is not documented. I will have to look into it.

**Comment by tomaae** [comment]
I dont remember any such warning when I was developing it, so it could be something related to newer library version. I should be able to replicate it in VM.

**Comment by Casuallynoted** [comment]
Also having this issue on my end. It takes up my whole HA log with warnings about the certificate, is there a way to fix it in the meantime? I've noticed that disabling the integration doesn't seem to change the logging.

**Comment by boced66** [comment]
> Also having this issue on my end. It takes up my whole HA log with warnings about the certificate, is there a way to fix it in the meantime? I've noticed that disabling the integration doesn't seem to change the logging.

Hello
Add this to your yaml
```
logger:
  logs:
    custom_components.truenas.truenas_controller: error
    custom_components.truenas.truenas_api: error

```
