### ISSUE TITLE
No response from host. 

### ISSUE THREAD

**Issue by khalfo44** [tomaae/homeassistant-truenas#104]
I can't seem to install the Add-on Integration. it keeps giving me "No response from host." message. I have created an API from my trunas scale image but I can't seem to connect tot it.

<img width="294" alt="image" src="https://github.com/tomaae/homeassistant-truenas/assets/128128989/99582776-8b0e-4fa0-ad2f-95f07aa9b8dc">

Anyone had this issue before?

Note: I have tried enabling/disabling Use SSL & Verify SSL certificate options. still same issue.

**Comment by khalfo44** [comment]
I have only choose "Use SSL" option, and it's giving me the following message:

<img width="304" alt="image" src="https://github.com/tomaae/homeassistant-truenas/assets/128128989/5eaf4258-ac90-4437-97de-48f202bf4550">

I know I have created the API, so I'm not sure what's missing...

<img width="1247" alt="image" src="https://github.com/tomaae/homeassistant-truenas/assets/128128989/26dd9c04-c005-4eee-a5d6-380dc248d299">

**Comment by tomaae** [comment]
seems like wrong ip, or HA is trying to access something different and it could be issue with your network setup.

**Comment by khalfo44** [comment]
Oh yeah maybe I'm using a reverse proxy, can I change the port number on HA ??

**Comment by khalfo44** [comment]
Just a quick update, I've added the Trunas port next to the host number and it worked.
