### ISSUE TITLE
[Bug] hacs package stopped working after moving to 2023.9.x

### ISSUE THREAD

**Issue by bmf7777** [tomaae/homeassistant-truenas#109]
## Software versions

 - Home Assistant version:  HA 2023.9.2
 - TrueNAS integration version:  v1.2.3
 - TrueNAS version: TrueNAS-SCALE-22.12.3.3

## Traceback/Error logs

no errors for truenas

**Comment by tomaae** [comment]
I guess this is related to #103? There have to be errors in log

**Comment by bmf7777** [comment]
Latest rev fixes startup issue
