### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by schettada** [tomaae/homeassistant-truenas#112]
## The entity IDs are not correct/changed with the latest version.

With the latest version 1.2.5, the entity IDs are missing the integration/device name in it. For example, the CPU usage entity ID now is sensor.cpu_usage, whereas before it was sensor.truenas_system_cpu_usage. This makes it difficult to identify while searching for an entity in cards or automations.  

## How to reproduce the issue
1. Go to the new entities created
2. Click on any of the entities
3. Go to the settings and look at the entity ID. 

## Expected behavior

Expect to see the device name as part of the entity id. 

## Screenshots
![image](https://github.com/tomaae/homeassistant-truenas/assets/16140432/a794e69d-b410-462e-a440-6682f748c397)

## Software versions

All fields in this sections are required.
 - Home Assistant version: HA 2023.09.2
 - TrueNAS integration version: v1.2.5
 - TrueNAS version: TrueNAS-SCALE-22.12.3.2

**Comment by tomaae** [comment]
thats intended change, as it was causing issues everywhere except system device.

**Comment by tomaae** [comment]
see #101
