### ISSUE TITLE
Question regarding adding server to integration

### ISSUE THREAD

**Issue by dbullendsl** [tomaae/homeassistant-truenas#113]
Over the last month I've had to delete and re-install the TrueNAS integration and all goes well for the installation, except for one factor, all the entities show up as "generic" entities without prepending the name of the device. In other words if I add a server with name "TrueNAS1" I get entities like sensor.pool_iocage_download, etc.  (I'm just using one entity here as an example, all the entities for the server have the same syntax.)

Maybe I'm way off base here and my memory is faulty but I thought that it used to appear as "sensor.truenas1_pool_iocage_download, making it possible to identify which server the data is coming from when there are multiple servers.

If I'm correct, what can I do to change the resultant entities (aside from manually editing).

**Comment by tomaae** [comment]
its already done and will be available in next update. see #101

**Comment by dbullendsl** [comment]
Thank you.
