### ISSUE TITLE
[Bug] Adding more than one truenas server, does not create the "System" entity for each

### ISSUE THREAD

**Issue by Kedryn** [tomaae/homeassistant-truenas#114]
## Describe the issue
Adding more than one truenas server, does not create the "System" device  for each one, messing all sensors of all servers in the same device. 

## How to reproduce the issue
add 2 or more truenas servers

## Expected behavior
a separate entity for each server, as per other entities that this integration creates

**Comment by tomaae** [comment]
![image](https://github.com/tomaae/homeassistant-truenas/assets/23486452/e453047f-628d-4b8e-899c-7fbfde5681f5)
![image](https://github.com/tomaae/homeassistant-truenas/assets/23486452/a92750fa-00c9-4a90-8b2a-f15b4800fcfa)
Works fine in master
