### ISSUE TITLE
[Feature] % of space for each pool

### ISSUE THREAD

**Issue by Kedryn** [tomaae/homeassistant-truenas#115]
## Is your feature request related to a problem? Please describe.
sensors gives Available space and total space
it would be nice to have also a % occupied  or % free

**Comment by tomaae** [comment]
hmm, not sure if we want to change it at this point. what woudl be benefit for this?

**Comment by Kedryn** [comment]
I use it, for example, to feed a graph of free space
![image](https://github.com/tomaae/homeassistant-truenas/assets/12759632/102a068c-0cc0-4d7c-b421-99653bf07e07)

it would be nice, for those with multiple pools so they wont need template sensors with calc for each pool.

**Comment by tomaae** [comment]
idea behind using actual free space was to have actual number to set alerts for cases where there are multiple pools with vastly different sizes.
For example, my setup looks like this:
High performance pool for apps/vms 1TB
General data pool 4TB
Backup pool 2TB

80% usage means something very different for each pool. But for example 200GB left if a meaningful alert, to consider cleanup or extension.
Percent looks better in dials and graphs, but when it comes to automation, I'm not sure.
We could probably add it as an attribute, there is no harm in that. But as sensor, I dont see much real use for automation.

I have more pools, but those are used as volumes, so free space there is not relevant as they are 99% full all the time anyway.

**Comment by Kedryn** [comment]
It's fine as an attribute. And you are right, it's mainly for display. At work, i've setup an Home Assistant with some sensors, and colors for ok/warning/critical, and gauges don't work well with values that are not %.

**Comment by tomaae** [comment]
fair, we can do that

**Comment by HikariNoKitsune** [comment]
Would like to kind of second this. I'm arguably not all that 'versed' in the realm of creating custom components and cards and such... and i've spent the last 3 hours trying to figure out how to get a simple Gauge Card to show me my Total Space available with the current used space to fill up the gauge. while yes there isn't any use for automation per say, Home Assistant has dashboards, which alot of us use for all sorts of things. And having the ability to easily just 'slap' this in on the dashboard would be amazing. 

Currently i'm having to manually set a 'maximum' value, which sort of gives me what i want.. but it doesn't reflect what the server truly would have. 

Arguably.. this is mostly just a fault of my own, as I just can't figure out how to make a custom anything to do what I want specifically lol... as in, I can't for the life of me figure out how to utilize anything within an 'attribute' lol. 

Also can't really seem to figure out how to get this thing to convert from GiB to TiB. Have everything say 58,845.64 GiB all the time is kind of meh lol. but again, that's a 'my fault' i think, although would be nice if it 'just did it' like most other things.
