### ISSUE TITLE
[Feature] Reconfigure existing integration entries

### ISSUE THREAD

**Issue by MrTastyBiscuits** [tomaae/homeassistant-truenas#116]
## Is your feature request related to a problem? Please describe.
I would like to be able to change the settings of an existing integration entry without deleting it (change of ip/hostname of the server, ssl settings).

## Describe the solution you'd like
As with many other integrations, it would be nice to have a "Configure" button next to each integration entry on the integration page. 
When pressed, it would open the same dialog box as during the initial configuration and allow each setting of the existing entry to be modified.

## Describe alternatives you've considered
1. Modifying config files manually: I have looked around quickly in the config files but wasn't able to find the one that defines these settings. Maybe you can point me in the right direction, I'm not so well versed in HA config files location…
2. Deleting and recreating the entry: Unfortunately, I think that this may result in a loss of all the history of the current sensors (i.e. it would create new sensors and not link them back to the previous ones). This might not be the actual behaviour of the integration though, I'm unsure.
I would only consider doing this as a last resort.

## Additional context
I hope that my issue is described clearly enough and that I haven't missed something that's already there…
Many thanks for your work on this integration!

**Comment by tomaae** [comment]
hmm, never noticed such feature. can you give me some examples?

**Comment by tomaae** [comment]
ah I see, those are just integration options, not connection details and such.
truenas integration does not have any options, so its not available.

**Comment by tomaae** [comment]
as far as I know, you cannot change entries in data.entry.data, only data.entry.options.
so you will have to remove and readd.
if you remove the integration, restart ha and make sure all leftover entities are deleted, you should get same names as long as you name the entry in same way.
