### ISSUE TITLE
[Bug] Incorrect CPU usage value

### ISSUE THREAD

**Issue by psleutel** [tomaae/homeassistant-truenas#119]
## Describe the issue

The values in the integration don't match with the values in TrueNAS.
For example: sensor.cpu_usage gives 10.1% while TrueNAS gives 1%

## Expected behavior

A hoped that the values were more or less equal, taking in consideration that there is a time lap (update).

## Software versions

 - Home Assistant version:  HA 2023.10.5
 - TrueNAS integration version:  v1.2.5
 - TrueNAS version: TrueNAS-13.0-U5.3

## Additional context

I have this problem since the last upgrade of the integration after that is was broken in HA 2023.8.

**Comment by tomaae** [comment]
I have the same version on my main nas and cpu usage is correct there. I will need to see your debugs and diagnostics. Include screenshot of cpu usage graph at around the same time.

**Comment by psleutel** [comment]
I included a screenshot at the same time from Home Assistant integration and of TrueNAS
![HA-TrueNAS-Integration](https://github.com/tomaae/homeassistant-truenas/assets/67500974/02a59379-6393-4256-a7ba-bcd48ef55c17)

**Comment by tomaae** [comment]
Looks to be about the same value. I need to see full graph on truenas side too tho.

**Comment by psleutel** [comment]
I can't use it anymore so I give up.
