### ISSUE TITLE
Unable to connect to TrueNAS-SCALE-23.10.0.1

### ISSUE THREAD

**Issue by silentnyte** [tomaae/homeassistant-truenas#121]
## Describe the issue
Updated to TrueNAS-SCALE-23.10.0.1 and now cannot connect. Using integration version v1.2.5

## How to reproduce the issue
1. Add new integration

## Expected behavior
New integration added successfully

## Screenshots
![image](https://github.com/tomaae/homeassistant-truenas/assets/2430307/f8553f4f-e807-4b52-90a5-2ab220c37525)

## Software versions

 - Home Assistant version: 2023.10.1
 - TrueNAS integration version: v1.2.5
 - TrueNAS version: TrueNAS-SCALE-23.10.0.1

**Comment by ortigosano** [comment]
Hi! 
Same issue here:
TrueNAS-SCALE-23.10.0.1
HA OS running outside TrueNAS:  Version: 2023.11.1

Log Details:

`This error originated from a custom integration.

Logger: custom_components.truenas.truenas_api
Source: custom_components/truenas/truenas_api.py:111
Integration: TrueNAS (documentation, issues)
First occurred: 7:09:22 PM (11679 occurrences)
Last logged: 10:02:06 PM

TrueNAS 192.168.XX.XX unable to fetch data "reporting/get_data" (500)
TrueNAS 192.168.XX.XXunable to fetch data "reporting/get_data" (no_response)`

Thanks in advance!

**Comment by tomaae** [comment]
Duplicate to #102
