### ISSUE TITLE
[Bug] Incorrect information about memory capacity

### ISSUE THREAD

**Issue by Limych** [tomaae/homeassistant-truenas#124]
## Describe the issue

Sensor `truenas_system_memory_usage` contains incorrect data about memory capacity.

I have 16 GiB of memory installed on my system. As you can see in the pictures, 5 GiB of this is used by services, 10.1 is used as ZFS cache, and 0.5 GiB is free.

But the sensor attributes indicates that the total memory is 10.5 GiB, which is incorrect. In fact, this value is equal to (total_memory - memory_for_services).

## Screenshots

![Screenshot](https://github.com/tomaae/homeassistant-truenas/assets/8019701/0c6ab7c2-e8d0-46e7-9d55-31efe71cbbc3)

![Screenshot](https://github.com/tomaae/homeassistant-truenas/assets/8019701/e88d700f-1d60-402f-80d9-8aa02413ff19)

## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: v1.2.5
 - TrueNAS version:

**Comment by tomaae** [comment]
actually, truenas does not provide this value. its sum of used_value, free_value and cache_size-arc_value
it does nto have anything to do with what you see on that pie chart

**Comment by tomaae** [comment]
tested it using both core and scale, works according to graph.
