### ISSUE TITLE
[Bug] HAS report wrong storage used while integration is active

### ISSUE THREAD

**Issue by martin123ist** [tomaae/homeassistant-truenas#125]
## Describe the issue

After installing the integration I noticed that Home assistant was filling up the VM storage quickly, in a batter of 3 or so hours. The issue resets after a full system reboot.

## How to reproduce the issue

I'm not sure how to reproduce this.

## Screenshots

![Screenshot_20231123_220918_Home Assistant](https://github.com/tomaae/homeassistant-truenas/assets/83578996/e690ce3c-308b-4c7c-b048-63906fc2bed4)

## Software versions

All fields in this sections are required.
-->
 - Home Assistant version: HA 2023.11.3 
 - TrueNAS integration version: v1.2.5
 - TrueNAS version: TrueNAS-SCALE-23.10.0.1 

## Additional context

Home Assistant is running as a VM inside of truneas scale

**Comment by patrick3399** [comment]
![TrueNAS](https://github.com/tomaae/homeassistant-truenas/assets/99384328/35879314-6da8-4bfb-bc5c-fdaff20863b1)
I got the problem. Log too fast then let the log spam.
