### ISSUE TITLE
[Bug] Integration fails for TrueNAS Cobia

### ISSUE THREAD

**Issue by tedlefter** [tomaae/homeassistant-truenas#127]
## Describe the issue
After upgrading TrueNAS to Cobia, the integration stopped working.

Another issue to mention is that this failure repeats over an over again filling up the disk space with logs.
I suggest adding a delay to the retry and give up after a certain amount of failed attempts, and let the user re-initiate a retry from the UI.

## How to reproduce the issue
1. Upgrade TrueNAS to Cobia release
2. Configure integration
3. See error

## Expected behavior

Integration should configure successfully

## Software versions

 - HA Core 2023.11.3
 - Supervisor 2023.11.6
 - Operating System 11.1
 - Frontend 20231030.2
 - TrueNAS integration version: v1.2.5
 - TrueNAS version: TrueNAS-SCALE-23.10.0.1

## Traceback/Error logs

The failure logs are printed constantly filling up the disk.

TrueNAS 192.168.12.12 unable to fetch data "reporting/get_data" (500)
09:36:05 – (WARNING) TrueNAS (custom integration) - message first occurred at 09:33:34 and shows up 645 times
TrueNAS 192.168.12.12 fetching following graphs failed, check your NAS: ['load', 'cpu', 'arcsize', 'arcratio', 'memory', 'interface', 'cpu', 'arcratio', 'interface', 'cpu', 'arcratio', 'interface', 'cpu', 'arcratio', 'interface', ...]
09:34:31 – (WARNING) TrueNAS (custom integration) - message first occurred at 09:33:34 and shows up 160 times

**Comment by mikeluyten** [comment]
See #102

**Comment by tomaae** [comment]
duplicate #102
