### ISSUE TITLE
Upgrade to Cobia, creates log flood in Home assistant[Bug]

### ISSUE THREAD

**Issue by TwoWheelPro** [tomaae/homeassistant-truenas#128]
## Describe the issue
Log Flood with warnings Fills 240GB drive in hours.

## How to reproduce the issue
Upgrade TrueNAS Sscale server from 22 to 23.10.0.1

## Expected behavior
Limited concise logging.

## Software versions

 - Home Assistant version: 2023.11.2
 - TrueNAS integration version: 1.2.5
 - TrueNAS version: 23.10

**Comment by mikeluyten** [comment]
See #102

**Comment by tomaae** [comment]
duplicate #102
