### ISSUE TITLE
[Question] Integração sem Dados

### ISSUE THREAD

**Issue by TharcisioMelo** [tomaae/homeassistant-truenas#130]
![Screenshot_1](https://github.com/tomaae/homeassistant-truenas/assets/153294501/c5869d5f-3b8b-4608-be93-2b099d2badd1)
![Screenshot_2](https://github.com/tomaae/homeassistant-truenas/assets/153294501/cedc747b-fa6f-4062-abf6-b5f55c3e14f8)

ao tentar integra via IP, dava erro de host, então utilizei o site, na qual uso o tunnel do cloudfare para acessar, e fez login com a integração, mas não obtem nenhum dado do Nas. Gostaria de uma ajuda.

**Comment by Mushishi** [comment]
TrueNAS did some changes in 23.10 update but you can look here https://github.com/tomaae/homeassistant-truenas/issues/102 for the changes you need to make to this plugin to get around 80% working again.
