### ISSUE TITLE
[Bug] Issue Setting Up - Name Already Exists (with fresh device) - Setup Fails - "unable to fetch data"

### ISSUE THREAD

**Issue by j0hnby** [tomaae/homeassistant-truenas#132]
## Describe the issue
When setting up the integration on HASS, I enter my sever details, and the integration reports name already exists (it doesn't, I deleted it weeks ago - but have used the same time as before). 

After that I hit cancel, and HomeAssistant goes back to to the Integrations screen, and the new config that I just put in is showing there - but failing to set up. 

In the logs I can see it connecting to my TrueNAS server - as it gets details for it like hardware and so on

Big chunks of "unable to fetch data "reporting/get_data" (500)"

fetching following graphs failed, check your NAS: ['load', 'cputemp', 'cpu', 'arcsize', 'arcratio', 'memory', 'interface', 'interface', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface', 'cputemp', 'arcsize', 'memory', 'interface', 'interface']

Log file attached

## How to reproduce the issue
1. Home Assistant > Settings > Devices & Services
2. Add
3. TrueNas
4. Enter details - using FQDN of server, port (as my interface listens on non-standard port), API, SSL and Verify SSL Cert
5. Spins for a while, then comes up with "Name already exists." as an error - however, the instance is created, but stuck failing to setup

## Expected behavior

Server is added, and setup completed

## Software versions

 - Core 2023.12.3
 - Supervisor 2023.11.6
 - Operating System 11.2
 - Frontend 20231208.2
 - TrueNAS integration version: 1.2.5
 - TrueNAS version: TrueNAS-SCALE-23.10.0.1

[home-assistant.log](https://github.com/tomaae/homeassistant-truenas/files/13696102/home-assistant.log)

**Comment by tomaae** [comment]
cobia is not supported yet.
duplicate #102
