### ISSUE TITLE
[Question] I keep getting "No response from host." error

### ISSUE THREAD

**Issue by jerrymarshall2004** [tomaae/homeassistant-truenas#133]
Hey everyone 👋

I setup TrueNas for the first time yesterday and have HomeAssistant running in a VM inside of it.

Every time I try to setup this integration I get the error "No response from host.", regardless of if I use the actual IP of the server or truenas.local.

Any help would be very appreciated!

Thanks!

**Comment by Hercka** [comment]
Same. Treunas scale + haos in vm.

**Comment by Seyude** [comment]
I have the same issue. Have TrueNas Scale and HA running on a standalone NUC. The integration loads and has a connection. I can see my disks and this is correct. But all the sensors stay at 0 or 0%. Is there some setup needed in TrueNas that i missed?

**Comment by JMEAthletics** [comment]
I just had the same issue, but managed to get in by unchecking the "Verify SSL Certificate" box and checking the "Use SSL" box. (using truenas.local)

**Comment by tomaae** [comment]
"No response from host" is self explanatory. HA just dont have access to ip/port you specified.
You need to make sure that you are entering correct information and you network is working correctly.

**Comment by Hercka** [comment]
i guess that i found how to solve it.
i ping ha in VM to TrueNas and get:

`admin@truenas[~]$ ping 192.168.1.XX
PING 192.168.1.XX (192.168.1.XX) 56(84) bytes of data.
From 192.168.1.YY icmp_seq=1 Destination Host Unreachable
From 192.168.1.YY icmp_seq=2 Destination Host Unreachable
From 192.168.1.YY icmp_seq=3 Destination Host Unreachable
From 192.168.1.YY icmp_seq=4 Destination Host Unreachable
From 192.168.1.YY icmp_seq=5 Destination Host Unreachable
From 192.168.1.YY icmp_seq=6 Destination Host Unreachable
From 192.168.1.YY icmp_seq=7 Destination Host Unreachable
^C
--- 192.168.1.YY ping statistics ---
11 packets transmitted, 0 received, +7 errors, 100% packet loss, time 10240ms`

Check details here:
https://www.truenas.com/community/threads/vms-cant-see-host.88517/

i'll check tomorow

**Comment by Hercka** [comment]
fixed by adding bridge in truenas
