### ISSUE TITLE
[Bug] Temperature Units

### ISSUE THREAD

**Issue by Frankenberrypi** [tomaae/homeassistant-truenas#135]
## Describe the issue
Unit conversions don't seem to be working correctly for temperatures.  My home assistant instance used Fahrenheit for temperature units, it seems that temperatures are brought in without units and assumed to be in °F without conversion, despite actually being in °C.

## How to reproduce the issue
Set HA units to F, connect a TrueNAS device.

## Expected behavior
Temperatures from TrueNAS should probably be assigned units of "C" when they are created to HA can convert them as required.

## Screenshots
![image](https://github.com/tomaae/homeassistant-truenas/assets/8370483/17918998-3139-4de7-90c2-9ea53f5a6e31)
![image](https://github.com/tomaae/homeassistant-truenas/assets/8370483/fac61a20-ca73-4b26-a09f-f82306eb4472)

## Software versions

 - Home Assistant version: HA Core 2023.12.4, Supervisor 2023.12.0
 - TrueNAS integration version: 1.2.5
 - TrueNAS version: core 13.0-U6.1

**Comment by tomaae** [comment]
I'm pretty sure this should work in master. Can you test?

**Comment by Frankenberrypi** [comment]
I deleted the integration entry, did a re-download with "master" selected, followed by a restart and re-setup of the integration.  The behavior seems to stay the same.  From the debug log:
```
    "truenas": {
      "version": "0.0.0",
      "requirements": []
    }
```
...and
```
        "ada8": {
          "name": "ada8",
          "devname": "ada8",
          "serial": "**REDACTED**",
          "size": 3000592982016,
          "hddstandby": "ALWAYS ON",
          "hddstandby_force": false,
          "advpowermgmt": "DISABLED",
          "acousticlevel": "DISABLED",
          "togglesmart": true,
          "model": "ST3000VN007-2E4166",
          "rotationrate": 5900,
          "type": "HDD",
          "temperature": 33
        }
```

![image](https://github.com/tomaae/homeassistant-truenas/assets/8370483/cfba7b28-6e5e-4d65-8637-44a75eb51a20)

**Comment by tomaae** [comment]
tested in master, works fine
