### ISSUE TITLE
zero-sensor-values

### ISSUE THREAD

**Issue by makisHr03** [tomaae/homeassistant-truenas#136]
Issue Description
Today, I installed TrueNAS SCALE on my server and integrated it with Home Assistant (HA). Upon configuring the integration, I noticed that all the sensors related to temperature, CPU load, and RAM load are showing values of 0.

![image_6](https://github.com/tomaae/homeassistant-truenas/assets/127298005/7226f1dd-fbd5-41e8-b5d8-c5cbc347df7b)

Software Versions
Home Assistant Version: 2023.12.0
TrueNAS Integration Version: v1.2.5
TrueNAS Version: TrueNAS-SCALE-23.10.1

I'm reporting this issue for further investigation and resolution.

Thanks for help!

**Comment by tomaae** [comment]
duplicate #102
