### ISSUE TITLE
Real unique id

### ISSUE THREAD

**Issue by djiesr** [tomaae/homeassistant-truenas#138]
## Is your feature request related to a problem? Please describe.

When I had à TrueNAS serveur, the sensor did'nt get a unique id. Like:

Temperature = sensor.temperature_3
Uptime = sensor.uptime_2
CPU usage = sensor.cpu_usage

Then, when you make a automatisation ou the dashboard, you have to check inch sensor to be sure it is the TrueNAS.

## Describe the solution you'd like

Had a unique id with the server name like : 

Temperature = sensor.truenas_temperature
Uptime = sensor.truenas_uptime
CPU usage = sensor.truenas_cpu_usage

## Describe alternatives you've considered

I understand that's wasn't a good solution for everyone have already install the integration, but you can had a option to use the old id or the new id.

That will be more pleasant for multi server to.

## Additional context

If you not consider to do that, please, juste tell me what I have to modify to do it.
Thanks!

**Comment by krzysiek2788** [comment]
As far as I know there was unique ID with naming like: **Temperatur = sensor.truenas_system_temperature** first part was name of device and second was real sensor so it was easy to find.

I think during resent major changes in Home Assistant regard naming of entities, Integration didn't adapt so there need to be some changes made :)

**Comment by dudu7731** [comment]
it's really a problem, i have 2 truenas VM and all sensors are upside down with _2 or _3 ... can you resolve this please ? really need the server name in sensor id

**Comment by tomaae** [comment]
tested this in master, all entites are prefixed by integration name. so this cannot happen.
