### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by justcallmedudedude** [tomaae/homeassistant-truenas#139]
## Describe the issue
The entries `sensor.temperature`, `sensor.cpu_usage`, `sensor.memory_usage` and all `sensor.cpu_load`s all report a value of `0` with their respective units.

## How to reproduce the issue
1. Add a TrueNAS device
2. Access the sensors

## Expected behavior
Sensors should show a non-zero number consistent with what is shown in the TrueNAS GUI

## Screenshots
![image](https://github.com/tomaae/homeassistant-truenas/assets/62908371/2e6f9f0b-8fe1-4f21-bf92-2f7cad55d52f)
![image](https://github.com/tomaae/homeassistant-truenas/assets/62908371/96e85a45-cd10-4760-8deb-1b368d5bde9a)
![image](https://github.com/tomaae/homeassistant-truenas/assets/62908371/7d71240d-d6d7-4042-8063-5743122a15a3)

## Software versions
 - Home Assistant version: 2024.1.5
 - TrueNAS integration version: v1.2.5
 - TrueNAS version: TrueNAS-SCALE-23.10.1.1

## Diagnostics data
I am not sure how to find this.

## Traceback/Error logs
I am not sure how to find this.

**Comment by tomaae** [comment]
duplicate #102
