### ISSUE TITLE
[Bug] Hard disk temperature read fail.

### ISSUE THREAD

**Issue by MisfitPunisher** [tomaae/homeassistant-truenas#14]
## Describe the issue

Some disk drive temperature information is missing or 0.

## How to reproduce the issue

I removed some drive from the pool and set it online again (not the temperature read fail one), but same pool. The Ada0 is not upgrading temperature.

## Screenshots

I run my shell awk script to get de hdd temperature, and works well.

_#! /bin/sh

for i in $(sysctl -n kern.disks)
do
        DevTemp=`smartctl -a /dev/$i | awk '/Temperature_Celsius/{print $0}' | awk '{print $10 "C"}'`
        DevSerNum=`smartctl -a /dev/$i | awk '/Serial Number:/{print $0}' | awk '{print $3}'`
        DevName=`smartctl -a /dev/$i | awk '/Device Model:/{print $0}' | awk '{print $3}'`
        echo $i $DevTemp $DevSerNum $DevName
done_

With this result (right one):
root@Temido[~]# ./disktemps.sh 
ada5 **48C** K42249R001653 Lexar
ada4 **25C** Z52B666K ST2000VN004-2E4164
ada3 **33C** ZFL37NA3 ST2000DM008-2FR102
ada2 **27C** WD-WCC4M3LGH3 WDC
ada1 **27C** Z52BBEF6 ST2000VN004-2E4164
ada0 **25C** 5YD1DRGT ST2000DL003-9VT166

![Captura de pantalla 2022-04-14 a les 1 32 11](https://user-images.githubusercontent.com/51487107/163286708-2ca94082-665f-407b-a952-3e6d8e0ff520.png)
A Truenas Integration Screenshoot appears as 0 (also in developer tools).
## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version:

**Comment by tomaae** [comment]
is the temperature for ada0 visible in TrueNAS directly? If it is, I will need debugs.

**Comment by MisfitPunisher** [comment]
I cleared smart options of the HDD and it became to 27º. Will keep and eye on it!

**Comment by tomaae** [comment]
ok, remember to check in truenas gui too, if it can see data.

**Comment by MisfitPunisher** [comment]
Got it. In the GUI did not appear

El dv., 15 d’abr. 2022, 3:14, Tomaae ***@***.***> va escriure:

**Comment by tomaae** [comment]
yea, if it did not appear in truenas gui too, that will have to be taken care by truenas team.

**Comment by tomaae** [comment]
closing as this is not related to integration
