### ISSUE TITLE
[Bug] Higher CPU Usage with Master (1f937c8) vs v1.2.5

### ISSUE THREAD

**Issue by JagerSprinkles** [tomaae/homeassistant-truenas#142]
## Describe the issue
After updating to Master branch commit 1f937c8 for the update check frequency fix I noticed that my Truenas server is now using a lot more CPU than when using v1.2.5 of this integration.
On v1.2.5 my idle Truenas CPU load is about 1-2%
On 1f937c8 my idle Truenas CPU load is 6-7%

## How to reproduce the issue
1. Install v1.2.5
2. Wait some time for CPU stats to collect
3. Install 1f937c8
4. Wait some time for CPU status to collect
5. Compare

## Expected behavior
CPU usage should remain the same as v1.2.5 where it barely made a difference on the Truenas server. The updates in 1f937c8 seem to have increased CPU usage 3-4x. 

## Screenshots

![Screenshot 2024-02-06 165209](https://github.com/tomaae/homeassistant-truenas/assets/6476475/e6f4b876-3575-4148-bf7a-2f2791bbc5cb)

![Screenshot 2024-02-06 164822](https://github.com/tomaae/homeassistant-truenas/assets/6476475/ba99ff5d-f56b-463c-aa3b-b78d32a6405e)

![Screenshot 2024-02-06 164346](https://github.com/tomaae/homeassistant-truenas/assets/6476475/4c5233ce-b4ac-43f4-a3ef-39b239f5e4a9)

![Screenshot 2024-02-06 164938](https://github.com/tomaae/homeassistant-truenas/assets/6476475/d43e4cf0-13ae-4405-8ee4-5432b80ddad2)

The third and fourth screenshots show the difference before and after installing 1f937c8 and the idle CPU baseline being increased 3-4x.

## Software versions
 - Home Assistant version: 2024.1.6
 - TrueNAS integration version: 1f937c8
 - TrueNAS version: TrueNAS-13.0-U6.1

## Diagnostics data
Not sure what to collect for this,

## Traceback/Error logs
No errors or anything in the logs. I have my log level set to warning and there are no entries about this integration. I can collect info/debug logs if they are required to troubleshoot this issue.

## Additional context
No other changes were made to the Truenas or Home Assistant server. I had restarted both as well after changing integration versions with no change in CPU usage.

**Comment by tomaae** [comment]
oof, thats a lot. what kind of hardware do you use?

Try changing following like to 60 seconds and let me know.
[            update_interval=timedelta(seconds=10),](https://github.com/tomaae/homeassistant-truenas/blob/1f937c815ee13bace1abeb2debe8ff8a8d72e306/custom_components/truenas/coordinator.py#L44)

**Comment by JagerSprinkles** [comment]
My Truenas server has an intel xeon E5-1620 v4 so its an older cpu but plenty powerful.

I made the change you mentioned and it seems the cpu usage is back down to how it was before, barely noticeable. I guess 10 seconds was a little too frequent for my system. This integration is working great again now!

Also related to this update_interval, do you plan on making this configurable? Not sure the effort involved as I have not made a home assistant integration before but I feel it might be a feature someone would find useful.

Thanks again! This should be good to close out if you want.

**Comment by tomaae** [comment]
great.
I dont currently have plans to make it configurable. 60 sec is standard, 10 is there just for development.
Its fairly easy to make update interval configurable if its needed, thats not a problem.

**Comment by JagerSprinkles** [comment]
The 10 seconds makes sense for development. I have done similar with my projects.
I don't think I need to have the update interval configurable, I was just curious. I don't need to request features I won't use.

I am going to close this out now as it looks like everything has been working fine overnight.
