### ISSUE TITLE
Diagnostic Values are 0

### ISSUE THREAD

**Issue by Jarek2k** [tomaae/homeassistant-truenas#145]
## Describe the issue
Most of the sensors are reporting properly but all diagnostics (CPU Usage, Memory usage, Temperature...) are 0.
It seems not to be an individual case as you can see in the latest posts at https://community.home-assistant.io/t/truenas-integration/410431

## How to reproduce the issue
Check the TrueNAS integration page in HA

## Expected behavior
All diagnostic sensors should report the current values

## Screenshots
![image](https://github.com/tomaae/homeassistant-truenas/assets/22426372/ab732c88-8dcb-4cc0-9b21-6c97c4d9d0c3)

## Software versions

 - Home Assistant version:  HA 2024.2.0 
 - TrueNAS integration version: v1.2.5
 - TrueNAS version: TrueNAS-SCALE-23.10.1.3

**Comment by tomaae** [comment]
yes, cobia is not supported yes. its in the same thread
duplicate #102
