### ISSUE TITLE
[Bug]Renaming integration fails

### ISSUE THREAD

**Issue by MisfitPunisher** [tomaae/homeassistant-truenas#146]
When I create a new integration, and when I rename it, all the sensors remain with the same begining name. In my case apears the pool names, CPU, memory... etc... all **without the integration name at the beggining** of the sensor (TrueNAS in my case).

Adding the integration name at the beggining of all the sensors of truenas integration.

## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version:

**Comment by tomaae** [comment]
Yes, when you change name of the integration, entity names will not change. Thats normal behavior.
Tested it with esphome, same behavior, which makes sense. It could break dependent things otherwise.

**Comment by MisfitPunisher** [comment]
What I Can do to have again the same name??
