### ISSUE TITLE
[Bug] unable to fetch data (500)

### ISSUE THREAD

**Issue by jacobpearson** [tomaae/homeassistant-truenas#15]
## Describe the issue
Plugin returns error message in logs, all entities in HA report as Unavailable.
However, when viewing the entity, the plugin does correctly get the motherboard and TrueNAS version

<img width="1135" alt="Screen Shot 2022-04-16 at 10 08 38 AM" src="https://user-images.githubusercontent.com/7758812/163648336-d320764e-fed2-43f4-a3ca-cd5ce824f1af.png">

## How to reproduce the issue
- Add plugin via HACs
- restart HA
- Generate API key in TrueNAS, copy
- Configure IP/Hostname, API key in HomeAssistant for the TrueNAS machine
- restart HA

## Expected behavior
Entities should have some information populated.

## Software versions
 - Home Assistant version: HA 22.3 on HAOS 2022.04.0
 - TrueNAS integration version: 1.0.2
 - TrueNAS version: Core 12.0-U6

## Diagnostics data

> This error originated from a custom integration.
> 
> Logger: custom_components.truenas.truenas_api
> Source: custom_components/truenas/truenas_api.py:98
> Integration: TrueNAS (documentation, issues) 
> First occurred: 10:02:20 AM (5 occurrences) 
> Last logged: 10:06:20 AM
> 
> TrueNAS 192.168.0.10 unable to fetch data (500)

## Traceback/Error logs
Nothing corresponding in the TrueNAS messages log file

## Additional context
I'm running HAOS in a virtual machine, on the TrueNAS box I'm trying to collect stats from.

**Comment by tomaae** [comment]
See #9
