### ISSUE TITLE
[Bug] "division by zero" error

### ISSUE THREAD

**Issue by frakoch** [tomaae/homeassistant-truenas#152]
## Describe the issue

I just updated to master via HACS to test out the new version and immediately found this in the logs (+ the integration not loading). I have a pool that is offline, which might be the cause of this, but nevertheless the values should be sanitized before using them.

## How to reproduce the issue

not sure, I suppose offlining a pool

## Expected behavior

component should initialize and run :)

## Software versions

 - Home Assistant version: HA 24.04.3
 - TrueNAS integration version: d4cd011088aec3b58023126bce894e637ca95a56 (in case "master" update via HACS did work correctly)
 - TrueNAS version: scale 23.10.2

## Diagnostics data

```
Logger: custom_components.truenas.coordinator
Source: helpers/update_coordinator.py:315
Integration: TrueNAS (Dokumentation, Issues)

Unexpected error fetching BRAIN data: float division by zero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 104, in _async_update_data
    await self.hass.async_add_executor_job(self.get_pool)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 782, in get_pool
    self.ds["pool"][uid]["available_gib"]
ZeroDivisionError: float division by zero
```

**Comment by tomaae** [comment]
I will need debugs to see what happened there. Seems like you truenas is sending faulty data.

**Comment by tomaae** [comment]
It is actually caused by offline pool. How did you took the pool offline?
I will fix this when I get home.

```
'id': 7, 'name': 'tank', 'guid': 'XXX', 'path': '/mnt/tank', 'status': 'OFFLINE',
```

**Comment by da-anda** [comment]
HDDs are temporarily unplugged. Didn't want to deal with TrueNAS complaining about SMB shares pointing to a missing pool, permissions and what not

**Comment by tomaae** [comment]
ok, that should be easy to simulate in VM

**Comment by da-anda** [comment]
thanks. I can confirm it's working now. The only thing "missing" is that the sensor `sensor.NAME_datasets_POOLNAME` seems not to get created in this state, while all other related sensors (ZFS health etc) are still present (even though empty). Not a big thing, just something I noticed.

**Comment by tomaae** [comment]
do you mean size sensor for tank pool?

**Comment by tomaae** [comment]
I will look into it
