### ISSUE TITLE
[Question] How to configure Truenas acess

### ISSUE THREAD

**Issue by mariuste** [tomaae/homeassistant-truenas#156]
I am trying to set up the integration:
- homeassistant-truenas V1.2.5
- HA: Core 2024.4.4 / Supervisor 2024.04.0 / OS 12.2 / Frontend 20240404.2

I Installed the Add-on. It is visible in:
HACS -> Integrations -> TrueNAS

Now I want to configure it so it can control my server. However I fail at this step from the instructions:
> 2. Setup this integration for your TrueNAS device in Home Assistant via `Configuration -> Integrations -> Add -> TrueNAS`

Despite my best efforts, I can't find the entry `Configuration`. The closest thing I found in the Home Assistant menu structure are:
1) `Settings -> Add-ons`, but there is no entry for TrueNAS
2) `HACS -> Integrations -> TrueNAS` but this is only the landing page of the Add-On, there are no settings here

I feel like I am missing something.

Update: while writing this issue I found it. You have to add a new device first:
`Settings -> Devices & services -> Devices -> Add Device`, in this dialog it can be edited. I still don't know where the `Configuration -> Integrations -> Add -> TrueNAS` in the instructions comes from. I suggest updating the instructions.

**Comment by tomaae** [comment]
assuming you restarted HA after installing the integration, it could be issue with your browser cache.
clear you cache and it should show up
