### ISSUE TITLE
[Bug] - home assistant continuously reports that an update available

### ISSUE THREAD

**Issue by muddro1** [tomaae/homeassistant-truenas#160]
After upgrading to dragon fish 24.04.1, HA still reports an update available. Seems the naming convention is off.

![Screenshot_20240528-142459](https://github.com/tomaae/homeassistant-truenas/assets/15880479/e2085f9f-6672-4164-9b38-061f024bc5d0)

**Comment by slovdahl** [comment]
I also saw a repair for a TrueNAS update today with no update actually being available. But it's gone now without me doing anything about it. I think it said that the version to update to is "unknown" or something like that. Running CORE, version TrueNAS-13.0-U6.1. Integration version 1.3b2.

**Comment by slovdahl** [comment]
Still seeing the occasional repair saying an update is available.

**Comment by jpettitt** [comment]
Looks like if the version comes back unknown (like just after a home assistant restart) it reports an update available becasue `unknown != <the latest version>`.  Once the running version becomes available the update warning clears on my system.

**Comment by slovdahl** [comment]
I tried to read the code a bit and I get the feeling these `unknown` instances are defaults defined in code in the integration, and are just used as placeholders until something is actually returned from TrueNAS. Should `unavailable` be used instead @tomaae?

**Comment by tomaae** [comment]
no, unavailable is an entity state. that would just make it confusing.
it would be best if entities could be in unavailable state until first cycle is finished, but that may not be possible in current implementation.
