### ISSUE TITLE
[Bug] Integration does not work when HTTP redirects are enabled for truenas web interface

### ISSUE THREAD

**Issue by GrootOpperhoofd** [tomaae/homeassistant-truenas#161]
## Describe the issue
A clear and concise description of what the issue is.
I've enabled "Web Interface HTTP -> HTTPS Redirect" checkmark under System settings>General>GUI settings in truenas and the HA integration stopped being able to fetch data from truenas. I've tried to make a new entry but it just indicates "No response from host." when I tried to set it up. Renewing the API key has no effect but when I uncheck the redirect box everything works as expected again.

## How to reproduce the issue
Set the "Web Interface HTTP -> HTTPS Redirect" checkmark under System settings>General>GUI settings in truenas web interface

## Expected behavior
Truenas is accessible what the redirects are active.

## Software versions
 - Home Assistant version: 
   -  Core 2024.5.4
   - Supervisor 2024.05.1
   - Operating System 12.3 
 - TrueNAS integration version: V1.3b2 in HACS, 0.0.0 (According to HA interface under the integration page)
 - TrueNAS version: TrueNAS-SCALE-24.04.0

## Traceback/Error logs
Logfiles just repeat the following line:
"TrueNAS 192.168.x.x unable to fetch data "system/info" (no_response)"

**Comment by tomaae** [comment]
Works for me. Make sure that you have set integration to use ssl.

**Comment by GrootOpperhoofd** [comment]
I did tick the SSL box when setting up truenas in HA but was unable to get it to work before. Updated to latest version of truenas today and it seems to work for me now as well. Not sure if the update fixed it or a reboot truenas was enough but the problem seems to be gone.
