### ISSUE TITLE
[Bug] TrueNAS-SCALE-23.10.2 creating system device/entities without NAS prefix

### ISSUE THREAD

**Issue by arrikhan** [tomaae/homeassistant-truenas#162]
I just upgraded to today's version as of July 1st (I say this because its showing 0.0.0 in integration but found TrueNAS-SCALE-23.10.2 in related device info) and the system entities have no prefix where as the other entities now have a prefix (mine here is NexusTrueNAS).

There is a duplicate device entry for System with the prefix but the entities are unavailable and there are fewer (as per previous version) of them.

Example:

system>diagnostic> <-- no prefix
sensor.memory_usage <-- no prefix

NexusTrueNAS  system>diagnostic>
sensor.arc_ratio <--- unavailable

NexusTrueNAS Datasets>disks>
sensor.nexustruenas_datasets_mainvol_monitoring

**HA version** 
Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240610.1

**Comment by tomaae** [comment]
I dont see that issue, all my entities have name prefix.
Check which version you installed in HACS.

**Comment by arrikhan** [comment]
I had to uninstall and reinstall to resolve the problem.
