### ISSUE TITLE
Tried with Dragonfish ?

### ISSUE THREAD

**Issue by Deldion** [tomaae/homeassistant-truenas#163]
Has anyone tried this with Dragonfish release of TrueNAS Scale?

**Comment by Deldion** [comment]
To answer my question.
Yes everything is working on Dragonscale.

There is a false system update flag that is popping on HA upon reboot, but apart from that, everything works more than fine!!!

**Comment by tomaae** [comment]
Good to know. Can you take a screenshot of update entity?

**Comment by Deldion** [comment]
Ok, this is very strange...
When reloading the integration, I am getting this:
![Screenshot_20240706-140913.png](https://github.com/tomaae/homeassistant-truenas/assets/55108743/25195aef-87e4-4622-abe4-afffc1a1681f)

  
However, when I went into the integration and got to the update entity from there, it showed this:  
![Screenshot_20240706-141030.png](https://github.com/tomaae/homeassistant-truenas/assets/55108743/163bbfd1-3df5-482d-a420-bd8c22e8c247)

**Comment by tomaae** [comment]
looks like you were too fast.
I will think of how to filter out when version detection fails.

**Comment by Deldion** [comment]
New information!!!
Updating to 24.04.2.
Update was initiated from the integration.
Works great!

However. After the upgrade was installed on TrueNAS, got the following on the integration.

![Screenshot_20240709-235225.png](https://github.com/tomaae/homeassistant-truenas/assets/55108743/6e8f5d90-6a9a-4644-bd2a-715acccc6b63)

And this from the log:
```
This error originated from a custom integration.

Logger: custom_components.truenas.coordinator
Source: helpers/update_coordinator.py:312
integration: TrueNAS (documentation, issues)
First occurred: 11:24:46 PM (1 occurrences)
Last logged: 11:24:46 PM

Unexpected error fetching TrueNAS data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 96, in _async_update_data
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 427, in get_systemstats
    max(tmp_graph[i]["aggregations"]["mean"].values()), 2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

**Comment by rboe1** [comment]
After updating, I am in the same boat.

![image_2024-07-11_130425096](https://github.com/tomaae/homeassistant-truenas/assets/175332053/94d6483c-b051-4f47-b079-37d6fac8d892)

**Comment by tomaae** [comment]
I had 24.04.2 for some time now and it works fine.
Seems like you have issue with CPU graph. Check in truenas UI if CPU graph is working. If it is, post debugs so we can see what is coming in via api.
