### ISSUE TITLE
[Bug] Network traffic is showing as zero 

### ISSUE THREAD

**Issue by Alister-Zeus** [tomaae/homeassistant-truenas#164]
## Software versions

 - Home Assistant version: 
 - Core 2024.7.2
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

 - TrueNAS integration version: 
v1.3b2
 - TrueNAS version: TrueNAS-13.0-U6.2

## Additional context

[home-assistant_truenas_2024-07-15T18-42-28.184Z.log](https://github.com/user-attachments/files/16238919/home-assistant_truenas_2024-07-15T18-42-28.184Z.log)
[config_entry-truenas-555d1dedcce422142e41a8785774e4a6.json](https://github.com/user-attachments/files/16238920/config_entry-truenas-555d1dedcce422142e41a8785774e4a6.json)
[home-assistant_truenas_2024-07-15T18-18-00.193Z.log](https://github.com/user-attachments/files/16238921/home-assistant_truenas_2024-07-15T18-18-00.193Z.log)

**Comment by herden-system** [comment]
Problem still exists.

**Comment by drzoidberg33** [comment]
Yep, I recently started using this integration and noticed the same on my Core system.

I dug into it a bit and this commit is what's causing the problem: https://github.com/tomaae/homeassistant-truenas/commit/a59ea1e901fbea72a8769e7d56effcf61585c412

I'm not entirely sure what the intent was with this because afaict this is completely redundant.

**Comment by drzoidberg33** [comment]
@tomaae sorry to ping you, but just wanted to find out exactly what the intent was for the above commit - I can submit a PR to fix it the issue reported here once I have a bit more info.

**Comment by tomaae** [comment]
No problem with a ping.
I'm currently too busy with work and life to dive into github stuff. I will certainly go trough everything, open or closed once I have everything in order, so dont worry about status or github automations.

**Comment by drzoidberg33** [comment]
Looks like the units of measurement are off once fixing the zero response issue.

I changed mine to just grab the raw value from the graph api and set the native unit to `UnitOfDataRate.BITS_PER_SECOND` ([here](https://github.com/tomaae/homeassistant-truenas/blob/2c5ed512dac389f3157df379453fd938149d9acd/custom_components/truenas/sensor_types.py#L403) and [here](https://github.com/tomaae/homeassistant-truenas/blob/2c5ed512dac389f3157df379453fd938149d9acd/custom_components/truenas/sensor_types.py#L421)) which seems to be what the raw value is representing, although I couldn't find any documentation verifying this - but my graphs look correct now.

Note this is for TrueNAS core, not sure if there are API differences with Scale.

![image](https://github.com/user-attachments/assets/107adc2f-f26f-47ba-afb8-b204c8eb4aa4)

![image](https://github.com/user-attachments/assets/378686d5-f533-4041-81ec-f7eac97345c5)
