### ISSUE TITLE
[Feature] Different Update Interval for sensors

### ISSUE THREAD

**Issue by Mausbiber** [tomaae/homeassistant-truenas#175]
## Is your feature request related to a problem? Please describe.
You can't say that, no.
However, it is strange when values such as CPU load and current network transfer rates are displayed, but are only updated every 60 seconds.

## Describe the solution you'd like
It would be nice if some of the sensors were updated every second.
Here I mean the sensors for CPU, RAM and network interfaces.
Everything else can stay as it is.

## Describe alternatives you've considered
As an alternative, I have changed the code so that the values are queried every 10 seconds.
However, this generates a certain CPU load due to the amount of values.
As a test, I also set it to 1 second, but after that the CPU on the NAS was permanently at 10-25% and I think the amount of data in the short time is not good for Home Assistant either.
That's why I would like only a few ‘time-critical’ sensors to be queried every second and the rest as usual.

**Comment by tomaae** [comment]
this wont be possible, pull integrations just cannot be used for real time monitoring.
use CPU load instead of CPU usage for that kind of info.
network should show average for last 60 second
