### ISSUE TITLE
[Feature] Add version number

### ISSUE THREAD

**Issue by TheOfficialMrBlah** [tomaae/homeassistant-truenas#183]
## Is your feature request related to a problem? Please describe.

Home Assistant shows version "0.0.0", as "0.0.0" is entered as the version in “manifest.json”.
[custom_components/truecustom_components/truenas/manifest.jsonnas/manifest.json](https://github.com/tomaae/homeassistant-truenas/blob/2c5ed512dac389f3157df379453fd938149d9acd/custom_components/truenas/manifest.json)

## Describe the solution you'd like

Add version number to manifest.json

**Comment by tomaae** [comment]
this is on purpose. it is more trouble in case of mistake, then its worth.
