### ISSUE TITLE
[Feature] Pull scheduled jobs into HA calendar

### ISSUE THREAD

**Issue by wigster** [tomaae/homeassistant-truenas#187]
## Is your feature request related to a problem? Please describe.
My TrueNAS backup NAS is mostly offline. I only boot it for backups and scheduled tasks by switchign the machine on from HA. Currently I have to keep track of all the tasks schedule manually in order to make sure the NAS is booted beofre the task is to start.

## Describe the solution you'd like
It would be great if the integration cold sync the task schedule and put it in a calendar, which I could then use to boot the NAS without keeping the two schedules in sync.

## Describe alternatives you've considered
Doing it manually.

**Comment by tomaae** [comment]
Is this really an issue? Its mostly set and forget setup.
