### ISSUE TITLE
[Bug] Show scrub start/stop/remaining as timestamp instead of epoch

### ISSUE THREAD

**Issue by hugalafutro** [tomaae/homeassistant-truenas#19]
## Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/30209689/164206086-81f845ce-e839-40f5-bada-b019947184ea.png)

## Describe the solution you'd like
Would like to see the times represented as HH:MM, something like output of `zpool status`
```
  scan: scrub in progress since Wed Apr 20 01:11:03 2022
        22.7T scanned at 640M/s, 21.9T issued at 617M/s, 28.1T total
        0B repaired, 77.75% done, 02:57:25 to go
```

## Describe alternatives you've considered
n/a

## Additional context
n/a

**Comment by tomaae** [comment]
It was a mistake. forgot to convert it for non system pools.
