### ISSUE TITLE
[Bug] No response from host

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [tomaae/homeassistant-truenas#20]
I am using TrueNAS 12.0.U1.1 and Home Assistant 2022.4.7
I could intall the integration via HACS, but when I try to connect to the TrueNas host I just get "No response from host". Is this a bug or maybe something missing in the installation description?

**Comment by tomaae** [comment]
thats quite an old patch level, so not sure.
you will need to debug the integration to get more info.

**Comment by Sesshoumaru-sama** [comment]
I made it work ... had to switch on the SSL service on the TrueNAS host.
