### ISSUE TITLE
[Feature] Merge with sdwilsh/hass-truenas?

### ISSUE THREAD

**Issue by sdwilsh** [tomaae/homeassistant-truenas#29]
I've been maintaining [sdwilsh/hass-truenas](https://github.com/sdwilsh/hass-truenas), and maybe we should try to share efforts instead of doing two of the same things independently.

**Comment by tomaae** [comment]
Not sure what you mean by merging.
I had a look at your integration. isnt everything already included?
If there is something missing, we can add it of course. 
I have plans for adding more features, but its tricky until IX fixes API response codes.

**Comment by sdwilsh** [comment]
I meant collaborate instead of working independently.  If you aren't interested, that's not a big deal.

**Comment by tomaae** [comment]
sure, what do you have in mind?

**Comment by andreclemente** [comment]
I think it is a great idea!

**Comment by tomaae** [comment]
Closing since there is no comunication
