### ISSUE TITLE
[Feature] Add sensor(s) for memory usage

### ISSUE THREAD

**Issue by DasBurninator** [tomaae/homeassistant-truenas#34]
## Describe the solution you'd like

Add a sensor for memory usage %, cached memory usage, and ZFS cache

## Describe alternatives you've considered

Single memory usage sensory with cached and ZFS cache as attributes

**Comment by tomaae** [comment]
hmm, what would be a use of it? general memory usage is not the most useful thing.
you can see zfs arc already

**Comment by DasBurninator** [comment]
If you are running a good bit of apps and or VMs it is nice to be able to monitor memory usage. Not much different than wanting to monitor CPU usage right?

Having sensor parity with what is available on the dashboard in TrueNAS itself seems reasonable. Memory usage is the last piece missing from that.

**Comment by Limych** [comment]
I support this request.

Just started using this component. And just not enough for my dashboard data on memory usage. But I also ask you to add sensors for using swaps: free space, total size and usage percentage. You can use one sensor, where the percentage is the main one, and everything else is attributes. This is related data.

My answer to why memory usage data is needed:
Yes, I know that ZFS takes up almost all the memory for its needs. But even up to 90% memory usage is normal for servers. It is not normal if more than this is used for a long time or, even worse, the data starts to go into swaps for a long time.

ARC is useful for tuning ZFS, but it's more useful to know the state of memory usage for tuning the entire server.

**Comment by Limych** [comment]
I propose to use a single principle for all sensors of memory usage (it can also be applied to sensors of disk usage): one sensor for each entity - memory, swap, cache, ZFS cache, - the main value of the sensor is the percentage of use, additionally in the attributes the total size and free size in bytes.

**Comment by tomaae** [comment]
I will have a look at what kind of data are available via API.
