### ISSUE TITLE
[Bug] TrueNAS Scale duplicating Devices when adding multiple integrations

### ISSUE THREAD

**Issue by mic-mccann** [tomaae/homeassistant-truenas#35]
## Describe the issue

When I add my two TrueNAS Scale instances to the homeassistant integration. The first integration of "AlphaNAS" creates AlphaNAS Disks, AlphaNAS Services, etc as Devices. When adding the second "BetaNAS" as another integration , it creates AlphaNAS Disks, AlphaNAS Services, AlphaNAS Disks, AlphaNAS Datasets, and BetaNAS System under the BetaNAS integration. When it should be BetaNAS Disks, etc. All but the System Devices seem to merge together between the two integrations and this is really annoying behaviour.

## Expected behaviour

The two Devices should be seperate and not weirdly "merged" devices.

## Software versions

 - Home Assistant version: HA 2022.7.7
 - TrueNAS integration version: v1.1.1
 - TrueNAS version: TrueNAS-SCALE-22.02.2.1

**Comment by tomaae** [comment]
not sure I understand. can you add some screenshots?

**Comment by mic-mccann** [comment]
I added AlphaNAS first then OmegaNAS and this issue pops up and "merges" the Devices together.

<img width="392" alt="Screenshot 2022-08-03 at 8 49 09 pm" src="https://user-images.githubusercontent.com/32098178/182591121-146e4f5f-9d61-41c4-908b-eb9c85c72531.png">


<img width="594" alt="Screenshot 2022-08-03 at 8 49 27 pm" src="https://user-images.githubusercontent.com/32098178/182591138-b68d3be2-ea53-4b1a-bf55-299bba06ded2.png">

<img width="389" alt="Screenshot 2022-08-03 at 8 49 58 pm" src="https://user-images.githubusercontent.com/32098178/182591131-3a4b9bf2-785f-4820-be50-3d7fb28bdb31.png">

<img width="591" alt="Screenshot 2022-08-03 at 8 50 13 pm" src="https://user-images.githubusercontent.com/32098178/182591134-7c4a0993-3ea1-4aab-aa82-13ff673e856a.png">

<img width="559" alt="Screenshot 2022-08-03 at 8 50 40 pm" src="https://user-images.githubusercontent.com/32098178/182591143-b289e3f0-74b9-42f2-a792-aac414b4e495.png">

**Comment by tomaae** [comment]
Ah, gotcha. This needs to be fixed.
