### ISSUE TITLE
TrueNAS Integration Missing data[Bug]

### ISSUE THREAD

**Issue by psleutel** [tomaae/homeassistant-truenas#40]
## Describe the issue

When I (re)Install the TrueNAS integration then I see the datasets and the Pools. Not even 1 minute later the datsets and pools don't show anymore

## How to reproduce the issue

1. (re)Install the TrueNAS integration
2. Open TrueNAS Datasets in Integration (all datasets are there => see screenshot)
3. Wait +- 1 minute 
4. Open TrueNAS Datasets in Integration (all datasets are gone => see screenshot)
5. Open 

## Expected behavior

I expected that the datasets should remain, same for the Pools.

## Screenshots

Uploaded

## Software versions

All fields in this sections are required.

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version: <!-- TrueNAS-12.0-U8.1
[TrueNAS_Integration_After_1minute.pdf](https://github.com/tomaae/homeassistant-truenas/files/9358276/TrueNAS_Integration_After_1minute.pdf)
[TrueNAS_Integration_After_Install.pdf](https://github.com/tomaae/homeassistant-truenas/files/9358277/TrueNAS_Integration_After_Install.pdf)

## Traceback/Error logs

  Nothing in errorlogs

## Additional context

Reinstalled HACS, jail, HA, Integration. Same problem again and again

**Comment by tomaae** [comment]
This is related to removal of non-existant datasets. Can you install master and run integration in debug mode? I have added debug messages for this.

**Comment by julienlarivee** [comment]
I got the same problem.
I reinstalled 1.2.1
Rebooted
Then after everything disapear, I did reload the home assistant integration.

[log truenas.txt](https://github.com/tomaae/homeassistant-truenas/files/9363195/log.truenas.txt)

**Comment by tomaae** [comment]
> 

Probably not the same issue. I dont see anything disapearing. Can you open new issue and go into more detail?

**Comment by julienlarivee** [comment]
Well I saw that my datasets where missing. So I went and installed the 1.2.0 version to see if the bug was still there.
After the reboot, I went in the integration and saw all the datasets. Less than a minute later they all disapeared.
So I came here to write a bug report, but this issue was already filled.

So I took @psleutel How to reproduce and did it while reinstalling the version 1.2.1.
Again, I got the same result as @psleutel.
I don't see how this is a different issue and I don't want to duplicate it.

**Comment by tomaae** [comment]
ah ok, you said that everything disappeared. if its just datasets, install master and run debug again. it contains additional debug information I will need to see.

**Comment by julienlarivee** [comment]
Sorry for the confusion here.

Not sure if it's how to do it.
I deleted the trunas folder under custom_components in my config.
Then downloaded the master branch zip, took the truenas folder under custom_components and pasted it in my config.
Rebooted.
Waited until the dataset disappeared.
Reload the integration.
Waited again until the dataset disappeared.

Hope this one will help.
[log.truenas.txt](https://github.com/tomaae/homeassistant-truenas/files/9366263/log.truenas.txt)

**Comment by tomaae** [comment]
You can select master in HACS version selection, no need to do it manually.
I think I foudn the issue, can you test master again? No need for debugs if it works.

**Comment by psleutel** [comment]
I've installed the master in HACS and did then the integration. 
Datasets ar initially there but dissapear again after about 1 minute.
Sorry for this

**Comment by psleutel** [comment]
Hi @tomaae 
After the previous I got the message from HACS to upgrade TrueNAS integration towards Version 1.2.1 and believe it or not, now it works and the datasets don't dissapear anymore. Maybe something others can try aswell and see if this works for them aswell

**Comment by tomaae** [comment]
that should not be possible, certainly not with 1.2.1
I suspect there is something messed up with HACS and files are not updated properly. you most likely ended up with master, at least partly.
I would recommend removing integration, then all its files manually and install it again via HACS.

**Comment by julienlarivee** [comment]
I installed Master, rebooted and waited 10 minutes. 
It seems to be working. The datasets are still there.
Thank you!

**Comment by tomaae** [comment]
perfect, will release it in few minutes.
