### ISSUE TITLE
Home Assistant integration devices list contains old version devices [Bug]

### ISSUE THREAD

**Issue by julienlarivee** [tomaae/homeassistant-truenas#41]
## Describe the issue

In the Home Assistant integration, the devices are duplicate.
One with Firmware: TrueNAS-13.0-RELEASE
Another with Firmware: TrueNAS-13.0-U1.1

## How to reproduce the issue

Go to Prameters > Devices > TrueNAS

## Expected behavior

Only get one device per category. The one from the current version on the TrueNAS installation.

## Screenshots

![image](https://user-images.githubusercontent.com/55027006/185155414-1c1055be-28f3-44b7-936e-50ba87ae7090.png)
![image](https://user-images.githubusercontent.com/55027006/185155525-b85e0796-2ad0-4158-9c7b-3e1d9c1c9cd1.png)
![image](https://user-images.githubusercontent.com/55027006/185155618-91e51a02-3eb7-43b3-804c-8af5c97ac189.png)

## Software versions

 - Home Assistant version: HA 2022.8.5 
 - TrueNAS integration version: HACS 1.2.1 
 - TrueNAS version: TrueNAS-13.0-U1.1

**Comment by tomaae** [comment]
Nothing I can do about that. You will have to remove those manually, or remove your device from HA and add it again.

**Comment by tomaae** [comment]
No, its one time thing. I needed to change how devices are identified to support multiple instances of truenas. So they were not all bunched into one device.
Just remove your truenas from HA and readd it. It will be fixed.

**Comment by julienlarivee** [comment]
Thanks. Appreciated
