### ISSUE TITLE
Unable to fetch data "update/check_available" (504)[Bug]

### ISSUE THREAD

**Issue by julienlarivee** [tomaae/homeassistant-truenas#43]
## Describe the issue

When adding the integration, the only device found is System.
Also, around once per minute, all the entities in System are going unavailable and then they come back with a value of 0. They never get a valid value.

## How to reproduce the issue

Install the integration version 1.2.1 or 1.2.3
Go and check the device and the entities in the integration page.

## Expected behavior

Get all the devices (Disks, Datasets, ...).
The entities would not become unavailable and they would update their values.

## Software versions

 - Home Assistant version: HA 2022.8.6
 - TrueNAS integration version: 1.2.1 and 1.2.3
 - TrueNAS version: CORE 13.0-U1.1

## Diagnostics data

[config_entry-truenas-aa21eccbe3d0182fdcbc5938b51657d8.json.txt](https://github.com/tomaae/homeassistant-truenas/files/9436366/config_entry-truenas-aa21eccbe3d0182fdcbc5938b51657d8.json.txt)

## Traceback/Error logs

Cette erreur provient d'une intégration personnalisée

Logger: custom_components.truenas.truenas_api
Source: custom_components/truenas/truenas_api.py:99
Integration: TrueNAS (documentation, issues)
First occurred: 15:54:59 (60 occurrences)
Last logged: 16:26:05

TrueNAS 192.168.1.5 unable to fetch data "update/check_available" (504)

## Additional context

Tested also with 1.1.1 and 1.2 and everything is fine.

**Comment by tomaae** [comment]
Error 504 is gateway error, check why your truenas is unable to get update info.

**Comment by julienlarivee** [comment]
I am not entirely sure what I am looking for here.

I did a couple of tests and nothing seems conclusive.

Here's what I tried:
- I can listen to music and movies from my NAS to other devices without interruption.
- I can acces the NAS folders, create, modify and delete files too.
- I did SMART diagnostics on the NAS HDD and it's fine.
- I looked if all the Ethernet cables where correctly pluged in.
- I rebooted my modem, router, NAS and HA. Nothing changed.
- From HA I SSH into my NAS. I kept calling commands for 2 minutes strait and always get a fast result.
- I tested the integration version 1.1.1, 1.2, 1.2.1 and 1.2.3. Only 1.1.1 and 1.2 worked.
- I installed an old HA backup wich I know the integration was working. It was working. I updated the integration to 1.2.3 and it stopped working.
- I looked all HA integrations and it's the only one not responding.

The only clue I got here is that older versions of the integration where working.
If you got any other ideas on how I can diagnose this, please let me know.

**Comment by tomaae** [comment]
older versions will work because update integration is not implemented there yet.
I didnt mean truenas features. click on check for updates in truenas and we will see, best to check truenas logs after that too. I assume its access to outside is a problem why it is giving such an error. I need to confirm that.

**Comment by julienlarivee** [comment]
Like this?
![Capture](https://user-images.githubusercontent.com/55027006/187033889-cdfa9825-7d48-48e1-93c5-1350e5db871e.PNG)

And the log here?
![Capture2](https://user-images.githubusercontent.com/55027006/187033891-b735983d-3068-483e-89d9-e0161750ae54.PNG)

**Comment by tomaae** [comment]
ok, that is weird. certainyl not what I expected.
can you debug the integration?

**Comment by julienlarivee** [comment]
Sure
[debug.txt](https://github.com/tomaae/homeassistant-truenas/files/9439045/debug.txt)

**Comment by tomaae** [comment]
debugs show connection working and failing only on external update check.
I'm not sure why truenas api would respond like that if its working in UI.
I assume you normally update using truenas ui without issue?

**Comment by julienlarivee** [comment]
Ok I did some more digging and I found the cause.
The name of my Pi-Hole inteface has changed for some reason, so Pi-Hole was kind of stucked.
Reconfigured, and rebooted it and now Pi-Hole and the TrueNAS integration are working properly.

Sorry for everything.
By the way, Thank you for your great integration, and for your always fast support.

**Comment by tomaae** [comment]
no problem at all.
what did pi-hole caused there tho? since manual check for update worked, I dont understand what happend.

**Comment by julienlarivee** [comment]
Well I am not really sure, but usually, the dns request is sent to pi-hole. If for some reason, it can't be answered, it then try a second dns which is google. So if Pi-hole is down, there shouldn't be any problem.

In this case, when I checked for the update on TrueNAS, it was working, but had a feeling it was slow. I don't know if there is a timeout in the api that would of cause that in the integration side?

**Comment by tomaae** [comment]
hmm, could be that truenas api does handles dns differently.
I will need to change implementation for update check query, so it wont stop integration in case of such failure.
