### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by WalkeLee** [tomaae/homeassistant-truenas#45]
## Describe the issue

此错误来自自定义集成。

Logger: custom_components.truenas.config_flow
Source: custom_components/truenas/config_flow.py:76
Integration: truenas (documentation, issues)
First occurred: 22:18:38 (1 occurrences)
Last logged: 22:18:38

TrueNAS connection error (no_response)

## Software versions

 - Home Assistant version: Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
前端版本： 20220802.0 - latest
 - TrueNAS integration version: 
v1.2.3
 - TrueNAS version: TrueNAS-SCALE-22.02.3

## Additional context

![网页捕获_2-9-2022_214017_192 168 50 75](https://user-images.githubusercontent.com/39288935/188170288-ecb4b9f5-218d-4e3c-8ad6-e988f61a72e8.jpeg)

It is not possible to ping truenas in Home Assistant

**Comment by tomaae** [comment]
Not sure what you are asking. I can see there is no response from your truenas.

**Comment by WalkeLee** [comment]
I'm sorry I forgot network bridging because it was running in TrueNas. Please turn off this feedback and have a good day.
