### ISSUE TITLE
Datasheet usage not showing in HomeAssistant

### ISSUE THREAD

**Issue by LudiusB** [tomaae/homeassistant-truenas#47]
Hey, just setup TrueNAS and saw your Integration via HACS in HomeAssistant.
But my HA cannot read the datasheet usage.

for my current test setup i have "pool1" with datasheets (pics, vids,music,...) HomeAssistant Sensor for the Pool is correct and showing in Homeassistant. when i delete oder copy files it shows up, but not for the Subfolders. (sensor.truenas_datasets_home_nas_backups)

Any Idea?

**sry for my bad english, it is not my native language**

**Comment by tomaae** [comment]
I guess you mean datasets, but I have no idea what is your issue about.

**Comment by LudiusB** [comment]
yeah datasets not datasheets... 
![image](https://user-images.githubusercontent.com/111220285/192728850-0c51dfbd-9550-4f25-82ae-60cc411ada81.png)
in the Dataset 'backups' are about 15gb of files and iso's.'Freier Speicherplatz/Free disk Space' is updating like it should but not the Dataset usage.

Running:
TrueNAS-13.0-U2 on dedicated hardware
HomeAssistant 2022.9.4 on proxmox vm in another rig

**Comment by tomaae** [comment]
I see, can you provide diagnostics and debugs?
