### ISSUE TITLE
Sending commands

### ISSUE THREAD

**Issue by beyondtenor** [tomaae/homeassistant-truenas#50]
Hello! Sorry if this isn't best way to do this. I have a poweredge server that I run SCALE on directly, and I manually set fan speeds  based on situations to control noise thresholds. This is done via an ipmitool shell command. Is it possible to use this integration to send a command for the machine run in its shell? The webui for SCALE doesn't seem to like mobile devices in the CLI. If not, no big. Just thought I'd ask!

**Comment by tomaae** [comment]
yes, I have a script like that on boot as well.
but no, it is not possible using this integration, since it uses API.
