### ISSUE TITLE
[Feature] total volume space and disc information

### ISSUE THREAD

**Issue by MisfitPunisher** [tomaae/homeassistant-truenas#52]
## Is your feature request related to a problem? Please describe.

Hi folks, can be possible to have the total volume space sensor (or attribute), and and attribute on a disk sensor related to the pool that is member?? 

## Describe the solution you'd like

Add some new sensor or attribute of the total pool space and attribute on the disk sensor related to the pool

**Comment by tomaae** [comment]
Added to pools.
But I wont be adding it to disks, as they contain physical data, not logical.
