### ISSUE TITLE
[Bug] No Error, Just Fails

### ISSUE THREAD

**Issue by wormuths** [tomaae/homeassistant-truenas#54]
## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version:

**Comment by tomaae** [comment]
I cant do anything without any info. Make sure to fill the issue template with as much info as there is.

**Comment by wormuths** [comment]
Sorry about that.  There really isn't much information to tell.  I follow the instructions perfectly, and I get no error message.  It just times out or something.  What would be most useful to start troubleshooting this?  I'm not sure what makes it fail, but I'd love to get it working.

**Comment by tomaae** [comment]
versions, screenshots, diagnostic data, HA log. just provide everything you can.

**Comment by wormuths** [comment]
I just noticed the information isn't there on the bug report.  I put all that in when I created it...  

Home Assistant 2022.11.2
TrueNAS Core 13.0-RELEASE
Integration v1.2.3

The integration installs, and I clicked add...

![Start](https://user-images.githubusercontent.com/47436307/201536084-051c9a00-e652-49a3-a7bb-a981ab66d954.png)

All I get is this...

![Finish](https://user-images.githubusercontent.com/47436307/201536109-28dc178c-b867-434f-a792-fedee2628df0.png)

I've tried all sorts of various combinations of SSL, https:// in the URL, etc...  Same result.  If I put "https:" in the URL i get a "No response from host" error.  My firewall logs don't show anything being blocked, but HASS shows connection errors...

======================================

This error originated from a custom integration.

Logger: custom_components.truenas.truenas_api
Source: custom_components/truenas/truenas_api.py:44
Integration: TrueNAS (documentation, issues)
First occurred: 12:15:53 PM (4 occurrences)
Last logged: 12:44:19 PM

TrueNAS 172.16.1.200 unable to fetch data "pool" (503)
TrueNAS https://172.16.1.200 unable to fetch data "pool" (no_response)

=======================================

This error originated from a custom integration.

Logger: custom_components.truenas.config_flow
Source: custom_components/truenas/config_flow.py:76
Integration: TrueNAS (documentation, issues)
First occurred: 12:15:53 PM (4 occurrences)
Last logged: 12:44:19 PM

TrueNAS connection error (503)
TrueNAS connection error (no_response)

=======================================

I'm still tinkering in the firewall, but I haven't found any rule which may be blocking this from connecting...

Thanks,
Steve

**Comment by tomaae** [comment]
I have never tried it with 13.0 release version, there could have been some bug.
503 is service unavailable error. seems like there is something broken on truenas side.
I would recommend to actually update your truenas.

**Comment by wormuths** [comment]
Good day,

That would not surprise me.  I have found there is another issue with a networking configuration I have reported to them.  It prevents me from updating at the moment.  My TrueNAS works fine on 13.0, but if I update beyond that all my jails lose internet connectivity.  Maybe I'm just special.  LOL

https://ixsystems.atlassian.net/browse/NAS-118026

Something under the hood with networking did change along the way with them.  The 503... is there a specific service your integration relies on being enabled on the TrueNAS side to check?

Steven

**Comment by tomaae** [comment]
Do they really lose internet connectivity or just DNS? I had such issue with truenas.
Solved it by using resolv.conf syntax in configuration field:
![image](https://user-images.githubusercontent.com/23486452/201567614-9834c2ee-226c-45f8-839b-efa8e3f989a4.png)

Cant check the ticket, appearantly I dont have access to view it.

I'm accessing official API, I dont think you can control it in any way (officially).

**Comment by wormuths** [comment]
Yeah, sorry.  DNS.  

![Post](https://user-images.githubusercontent.com/47436307/201568073-9ab5e7d6-1ebb-4918-8b56-defb2056d811.png)

![Settings](https://user-images.githubusercontent.com/47436307/201568231-a92abdfa-69d6-4435-a1d7-c2dcbfd7cf69.png)

**Comment by tomaae** [comment]
yea, you can try to put it into resolver like I did.
DNS server entries in jail configuration never worked for me, even on 12.0
