### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by rVlad93** [tomaae/homeassistant-truenas#57]
I'm getting the following error when trying to connect to the server:

![image](https://user-images.githubusercontent.com/60452666/202577029-5222d161-2beb-470e-af9b-d203c9a45d69.png)

## Software versions

 - Home Assistant version: HA 2022.11.1 
 - TrueNAS integration version:  v1.2.3 
 - TrueNAS version: SCALE-22.02.4

**Comment by tomaae** [comment]
That is not a bug, its a correct error. check your connection
