### ISSUE TITLE
[Bug] temperature sensors showing as wrong unit of measure 

### ISSUE THREAD

**Issue by muddro1** [tomaae/homeassistant-truenas#58]
## Describe the issue

All temperatures showing the Celsius value but with Fahrenheit unit of measure. Ie. If a disk is 40 C, it shows as 40 F. If I manually edit the sensor to show in Celsius, it converts 40 as if it were fahrenheit.

## Expected behavior

The value of the sensor is correct but the unit of measure is wrong (should be Celsius, not fahrenheit)

## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version: 
TrueNAS-SCALE-22.02.4

**Comment by tomaae** [comment]
That is not on integration side.
Provided values and native unit is celsius, any conversion or unit change is done by HA.
