### ISSUE TITLE
Failed to set up integration

### ISSUE THREAD

**Issue by kcb064** [tomaae/homeassistant-truenas#59]
**Describe the issue**
Plugin fails to start with message: Failed to set up

**How to reproduce the issue**
Install like normal. Additional context may provide more insights.

**Software versions**
Home Assistant: 2022.12.3

TrueNAS integration version: v1.2.3
TrueNAS version: TrueNAS-SCALE-22.02.4

**Diagnostics data**
N/A

**Traceback/Error logs**
Logger: homeassistant.config_entries
Source: custom_components/truenas/truenas_controller.py:388
Integration: TrueNAS ([documentation](https://github.com/tomaae/homeassistant-truenas), [issues](https://github.com/tomaae/homeassistant-truenas/issues))
First occurred: 10:49:57 AM (1 occurrences)
Last logged: 10:49:57 AM

Error setting up entry NAS for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 124, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 388, in get_systemstats
    max(list(filter(None, tmp_graph[i]["aggregations"]["mean"]))), 1
ValueError: max() arg is an empty sequence

**Additional context**
I am running an AMD Ryzen 5 5600G with Radeon Graphics on my system. The Linux Kernel that Scale is using doesn't have support for temperature https://bit.ly/3PnmYzA I am wondering if the "get_systemstats" in the log is corresponding with this missing temperature? Is there a way to ignore this missing stat if it is indeed the issue?

**Comment by tomaae** [comment]
duplicate #55
