### ISSUE TITLE
[Bug] No response from host

### ISSUE THREAD

**Issue by NWalledge** [tomaae/homeassistant-truenas#64]
## Describe the issue

Go to setup integration - Put in all relevent details and then it says no response from host
All details are triple checked to be correct

## How to reproduce the issue
 "No response from host"

## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version:

**Comment by tomaae** [comment]
Its a valid error, integration was not able to get any response.
You need to make sure HA can access truenas web interface as you configured it.

**Comment by kfrancis1996** [comment]
I am also having this issue. New setup. Enter IP address for web interface, generate new API key. Uncheck box boxes.

TrueNAS-SCALE-22.12.0

 Home Assistant 2023.1.7 Supervisor 2022.12.1 Operating System 9.4 Frontend 20230110.0 - latest

**Comment by NWalledge** [comment]
> Its a valid error, integration was not able to get any response. You need to make sure HA can access truenas web interface as you configured it.

Ive tried everything it just wont work at all :(

**Comment by tomaae** [comment]
test your network connectivity from HA cli directly, as well as access to truenas API. from there you can investigate what is causing the issue.

**Comment by TheOfficialMrBlah** [comment]
I have exactly the same issue.

From the HA cli the NAS can be pinged via the hostname.tld but not exclusively via the hostname without .tld.

Interestingly, the dialog loads long when I enter only the hostname and responds with the error "No response from host." and loads short when I enter hostname.tld, but ends with the same error.

**Comment by tomaae** [comment]
well, if you are using forced ssl in truenas, that would be the case. non ssl API wont react in that setup.

**Comment by NWalledge** [comment]
> 

Doesnt work for me :(

**Comment by NWalledge** [comment]
> well, if you are using forced ssl in truenas, that would be the case. non ssl API wont react in that setup.

How do i change that?

**Comment by NWalledge** [comment]
> well, if you are using forced ssl in truenas, that would be the case. non ssl API wont react in that setup.

I dont have SSL on my TrueNAS

**Comment by tomaae** [comment]
try to access it from HA cli like I said

**Comment by NWalledge** [comment]
> try to access it from HA cli like I said

How do i do that?

**Comment by kfrancis1996** [comment]
i was able to resolve my issue. I had multiple NICs, i tried the secondary IP and it worked.

**Comment by tomaae** [comment]
> > try to access it from HA cli like I said
> 
> How do i do that?

login to HA shell, first ping just to ensure there is connection. then curl to try accessing web

**Comment by NWalledge** [comment]
> > > try to access it from HA cli like I said
> > 
> > 
> > How do i do that?
> 
> login to HA shell, first ping just to ensure there is connection. then curl to try accessing web

Pinging in HA shell i get 100% packet loss :(

**Comment by NWalledge** [comment]
Now what is weird is i can setup and also ping from HA to my Cloudflare tunnel to my TrueNas Scale....
My HA is a VM on my TrueNas Scale so maybe something there as pinging HA from TN neither of them see eachother...

**Comment by tomaae** [comment]
ah, right. thats a bug in scale, there is problem with internal bridge. should be fixed in next scale release.

**Comment by NWalledge** [comment]
Any more news on this?

**Comment by tomaae** [comment]
No idea, give it a try with new Scale update.

**Comment by NWalledge** [comment]
Tried it, still having an issue

**Comment by tomaae** [comment]
not much I can help with here. HA needs access to truenas, there is no way around it.
you may look into if you have some additional issue with access. could be your network, could be issues in virtualization layers.
