### ISSUE TITLE
[Question] Going unavailable takes a very long time

### ISSUE THREAD

**Issue by tre4b** [tomaae/homeassistant-truenas#66]
I am not sure if there is a way to change the polling of the services so that I can detect whether the server is still working or not.

Even if I turn off the server there is a long while between the server shutting down and emby changing the status to unavailable, and trying to automate actions around this just seems to do nothing.    I recognise this could just be how it is in Emby but wondered if there is a sensor that is polling more often so that a loss of the service is noticeable.   For going offline I can probably do something with Ping, but it would have felt neater if it was within this plugin.

**Comment by tomaae** [comment]
can you go more into detail? also, not sure what emby is.

**Comment by tre4b** [comment]
Sorry, I'm trying to do too jobs at once.  Emby is a media server like Plex that is running on the TrueNAS.  

The situation is that when the TrueNAS server goes offline the Integration remains showing the previous stats for a long while before going unavailable.   Thus reaction to the change to unavailable is very much delayed (and in fact I've not managed to get any automation to actually respond to it).     I understand this is basically the system timing out and marking it as unavailable, however I was wondering if any sensor was polling more often such that it stopped working quicker or whether such a thing would be possible.

**Comment by tomaae** [comment]
How long does it take for sensor to go offline?
Is there anything in HA log at time between server going offline and entity showing unavailable?

**Comment by tre4b** [comment]
Sometimes quite quickly other times not at all.

I actually shut down the Nas device last night at 10:30 (I have to do this every night as otherwise it keeps my wife awake and that can be painful 😉 ),   but this morning it was still showing as available with all data for the box showing.     The night before, it shut down and a minute later the alexa announced it was no longer available.  It seems to be circumstance related but the shut down is always the same as it is a chron script on the box (though I plan later to do this with the facility in this integration as that will be awesome)

trev
________________________________

**Comment by tomaae** [comment]
yea, within a minute should be normal.
check you HA log, there may be something related to why its not going unavailable.

**Comment by tre4b** [comment]
My whole log is swamped with alexa media player entries such that it is pretty unusable.  This is with the debugging option turned off so no idea what would happen if it was turned on!  I will have to download the file and see if I can find a way to filter the log somehow, maybe knock up some code.

**Comment by tre4b** [comment]
I found this interesting.  This morning the box is offline, but the information was showing as normal.  When I go into various Items it shows the stat as 3 Days ago, suggesting they may not have updated even when the box was on yesterday.

that said I also just received a message that a timer had completed when I have not initiated that timer today.  This may be suggesting I have other issues going on with my home assistant that could be confusing what I am seeing.

**Comment by tomaae** [comment]
Yea, you need to go through your HA log in detail. Maybe disable alexa media player integration for a while if its too spammy.

**Comment by tre4b** [comment]
I've now managed to turn off the extraneous messages in the debug log.  So far I have seen a reasonable response and it may be that this debug output in the log was actually also the source of the problem.  I will monitor it and confirm.

Trev

________________________________

**Comment by tomaae** [comment]
you mean debug choking fs? that must have been quite intense logging

**Comment by tre4b** [comment]
It does not seem to be that, so there is something else not happing.  The system still seems to hang on to the previous status of the box, even after it is shut down.  It shut down last night at 10:30 yet this morning at 0730hrs still showed the information for status and temp.  Checked the Logs and now it is quiet in there I could see no entries at all.   Should I enable debug logging for this integration?

[config_entry-truenas-dd2a9ffde27e14adf82e6edef18784d5.json.txt](https://github.com/tomaae/homeassistant-truenas/files/10837853/config_entry-truenas-dd2a9ffde27e14adf82e6edef18784d5.json.txt)

**Comment by tomaae** [comment]
yes, once you catch the error in debug, we will know more

**Comment by tre4b** [comment]
Issue is still there, I've got debugging switched on but cannot see what the issue may be.  I'm a bit confused that there is lots of Zigbee messages in the log with the debug tamed on on this plugin.  Should I share a copy of the log?

**Comment by tomaae** [comment]
please do

**Comment by tre4b** [comment]
I've been trying to do this however I am still not getting any information in the logs.  Not sure why this might be.  All I see is some start up warnings, otherwise the logs are clear.  I have double checked that the enable debugging is on for the integration, so I am assuming no log entries mean it is working fine and it is my setup and not the integration.
________________________________

**Comment by tomaae** [comment]
no, you will see logs of information every minute is you enable debugging for integration.
