### ISSUE TITLE
[Question] Resilver status?

### ISSUE THREAD

**Issue by crookedview** [tomaae/homeassistant-truenas#67]
Hello,

Possible I just missed this feature, but is it possible to see a pool's resilver (rebuild) status with this add-on?

Great add-on, by the way.  Thank you!

**Comment by tomaae** [comment]
there is no indication for resilver, unless pool status changes.
I hope nobody has to use it often enough to benefit from integration it with automation :)

**Comment by crookedview** [comment]
> there is no indication for resilver, unless pool status changes. I hope nobody has to use it often enough to benefit from integration it with automation :)

Ah, no worries.  I've been upgrading several of the disks in my NAS, so going through resilvers is a regular thing for me for at least a couple more days :).  It still shows the pool as healthy during the process, so I don't think that'll trigger anything.

Appreciate the reply though!
