### ISSUE TITLE
[Bug] HDD mapping is not consistent 

### ISSUE THREAD

**Issue by mcclown** [tomaae/homeassistant-truenas#77]
## Describe the issue
Initially my HDD were mapped as 

sda -> external SSD (1)
sdb -> 8tb(1)
sdc -> 8tb(2)

Then I added  a second external SSD, which caused the hard drive mapping to change.

sda -> external SSD (1)
sdb -> external SSD (2)
sdc  -> 8tb (1)
sdd -> 8tb (2)

This broke my long-term statistics and dashboards that were using this plugin. I fixed them up, although there wasn't a way to fix the long-term stats. That worked fine again until I added two more drives. At first the hot swap drives were fine:

sda -> external SSD (1)
sdb -> external SSD (2)
sdc  -> 8tb (1)
sdd -> 8tb (2)
sde  -> 16tb (1)
sdf -> 16tb (2)

Then I restarted my NAS and the drive assignments shuffled again

sda  -> 16tb (1)
sdb -> 16tb (2)
sdc  -> 8tb (1)
sdd -> 8tb (2)
sde -> external SSD (1)
sdf -> external SSD (2)

Each change breaks my dashboards and makes the long-term statistics for the HDDs useless.

## How to reproduce the issue
Add and remove HDDs, and reboot repeatedly.

## Expected behavior
Now, I know that this is an issue with TrueNAS not keeping drive assignments consistent. Still, if that's going to be the case, I think HDDs should be made available under a different entity name that will stay consistent, such as using their serial number.

## Software versions
 - Home Assistant version: 2022.11.1
 - TrueNAS integration version: v1.2.3
 - TrueNAS version: TrueNAS-SCALE-22.12.1

**Comment by mcclown** [comment]
I can probably take a look at making these changes in pull request, if this change would be something you would be willing to accept?

**Comment by tomaae** [comment]
not sure if there is some unique id available for disks via api. if there is it should be doable.
if you want to give it a go, feel free. right now I'm very busy, so cant have a look myself.

**Comment by mcclown** [comment]
> not sure if there is some unique id available for disks via api. if there is it should be doable. if you want to give it a go, feel free. right now I'm very busy, so cant have a look myself.

Serial number would be unique and that's coming back over the API. I think it would be the way to go. I had a quick look at it but I'll have to spend some more time on it in the next week or two

**Comment by aardvarkl** [comment]
I have been playing with just this issue in a script (written by someone else) that runs on TN and outputs drive temps direct to influxdb from which I graph in Graphana.
Initially it did sda/sdb etc, but everytime on a reboot they changed - which was a nusiance as I only want to graph the HDD temps, and not the SSD's
We now use serial numbers along with a hack mod from me that substitutes the serial numbers for a different string to make things a bit more readable

**Comment by tomaae** [comment]
thing is, I can only use API, so cant use any hacks on OS level. what IX provides is what I get.

**Comment by aardvarkl** [comment]
serial number would be good - along with maybe a mechanism of matching serial number to a user friendly name
something the equivalent of:
			if ($serial eq "152739404637") { $serial = "BootPoolSSD1"; }
			if ($serial eq "152739404858") { $serial = "BootPoolSSD2"; }
                        etc

I am going to change the "new" name to physical position in the NAS - just have to get around to it

**Comment by tomaae** [comment]
its not really that occaisonal. also if that would happen, it would crash the integration, which is even worse.
there has to be another way.

**Comment by aardvarkl** [comment]
OK - we don't want that.

**Comment by Dimand** [comment]
First up, great integration!

Why not just use serial number with a fall back to the dev identifier? At worst it will be as it is now and those of us with disks that do report a serial can enjoy a sane experience. Inconsistent entity id's are just a nightmare.

In addition to @aardvarkl's request above about user friendly names, HA already has this, as long as the entity id is consistent.
![image](https://github.com/tomaae/homeassistant-truenas/assets/1551981/d5be1b8b-b576-4893-b163-3e28ae00b3cd)


As a bit of a kludge, for now I will just see if it is at all possible to run a derivative sensor in HA based off these ones with a dynamic id from the attribute.

```
template:
  - sensor:
    - name: "{{state_attr('sensor.sda','Serial')}}"
      unit_of_measurement: "°C"
      state: "{{states('sensor.sda')}}"
      unique_id: "{{state_attr('sensor.sda','Serial')}}"
      
  - sensor:
    - name: "{{state_attr('sensor.sdb','Serial')}}"
      unit_of_measurement: "°C"
      state: "{{states('sensor.sdb')}}"
      unique_id: "{{state_attr('sensor.sdb','Serial')}}"
```
etc for each HDD. Will likely need a reload of the HA for each NAS reboot to work so not ideal.

**Comment by tomaae** [comment]
tested on both core and scale
