### ISSUE TITLE
CPU usage above 100% [Bug]

### ISSUE THREAD

**Issue by julienlarivee** [tomaae/homeassistant-truenas#78]
## Describe the issue
The CPU usage is above 100% in Home Assistant but not on the TrueNAS Dashboard

## How to reproduce the issue
I am currently running a linux vm inside truenas wich is transcoding video files. 
The cpu is quite high. Around 75-90%

## Expected behavior
Show the cpu usage like the one in the dashboard

## Screenshots
![image](https://user-images.githubusercontent.com/55027006/228069685-c9b0c2ea-3f8b-4017-b30e-f58db2921382.png)

![image](https://user-images.githubusercontent.com/55027006/228069877-629b4b4d-e3e4-4cf1-a031-b94560ee5e39.png)

## Software versions

 - Home Assistant version: 2023.3.6
 - TrueNAS integration version: 1.2.3
 - TrueNAS version: TrueNAS CORE-13.0-U4

## Diagnostics data
[config_entry-truenas-7a5b83130ee9cf754ba9c684b45ec46d.json.txt](https://github.com/tomaae/homeassistant-truenas/files/11083119/config_entry-truenas-7a5b83130ee9cf754ba9c684b45ec46d.json.txt)

**Comment by tomaae** [comment]
seems like your nas is reporting wrong data. can you debug it?

**Comment by julienlarivee** [comment]
[home-assistant.log](https://github.com/tomaae/homeassistant-truenas/files/11094012/home-assistant.log)
Hope there is all you need in it.

**Comment by tomaae** [comment]
So truenas is reporting something really weird here. Idle 100% system 96%?

```    
"legend": [
      "interrupt",
      "system",
      "user",
      "nice",
      "idle"
    ],
    "aggregations": {
      "min": [
        0.044981283522,
        96.94838281,
        97.943732712,
        97.943732712,
        100.0
      ],
      "mean": [
        0.070168899641,
        97.534423475,
        98.48254716728572,
        98.48442206357143,
        100.0
      ],
      "max": [
        0.10591442289,
        98.535371417,
        99.400916464,
        99.400916464,
        100.0
      ]
```
Try running mpstat or iostat to see if its problem with API or OS customization.

**Comment by julienlarivee** [comment]
I got this while on heavy load:
![image](https://user-images.githubusercontent.com/55027006/230918743-4c6cd5fb-f612-41d0-83fa-6e0ce548e757.png)

**Comment by tomaae** [comment]
ok, so its problem with API itself. Nothing I can do there unfortunately.

**Comment by julienlarivee** [comment]
No problem. Thanks

**Comment by tomaae** [comment]
I plan to look into it further, but no promisses at all. I may open issue with IX, but they are super slow to fix API things.

**Comment by rlewis187** [comment]
Doesn't TrueNAS report CPU usage as 100% x Number of cores?

https://www.truenas.com/community/threads/what-does-cpu-usage-mean-mine-is-often-100.61708/

**Comment by tomaae** [comment]
Thats how linux reports it, yes.
But core and scale reports cpu usage inconsistently via API. Core always reports 100% as all cores. Scale did that too durring my development, but it seems to be different now. Possibly a bug in API.

**Comment by tomaae** [comment]
seems to be fixed in API
