### ISSUE TITLE
Setup Error [No response from host.]

### ISSUE THREAD

**Issue by karharry** [tomaae/homeassistant-truenas#79]
Hello,

Current Setup:
HomeAssistant accessed with https (Let's Encrypt Certificate with DuckDNS). Local IP is xx.xx.xx.60
TrueNas running with http, no SSL. Local IP is xx.xx.xx.51

Setup HACS integration and then Truenas integration within HACS.
Restarted per the instructions.
Adding Truenas:
Name: TrueNas (left as is)
Host or IP: Tried with my TrueNas hsot name and the IP Address
API: pasted the created API

When trying with IP I tried with adding the Truenas port number, without port number
Still getting error [No response from host]

Any ideas? Maybe a service I need to enable on Truenas?

Thanks!

**Comment by tomaae** [comment]
no response means your ha cant access nas over network

**Comment by karharry** [comment]
OK. Thanks for that.
Assuming issue with my TrueNas config "hiding itself" from the Network.
HAOS connects with no issues to my Synology and everything else on my network, so is there maybe a setting I must change on TrueNAS Scale?

**Comment by tomaae** [comment]
login to your HA and try to access it from there. I know there was a bug accessing truenas if you were running HA as a container, but I think that should be fixed now.
I doubt its related to any scale settings.

**Comment by karharry** [comment]
This is now resolved.
I managed to connect to my TrueNas via static dns and the exposed port.
Thanks for the help though :)
