### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by lhvandersteen** [tomaae/homeassistant-truenas#87]
hello 

i have copied the custom component folder in my home assistant ( i have no hacs)  and then i installed the truenass addon
this was successful (master version)
after some hours it has finaly automatic connected
but most of the time it is showing entitie not available   but sometimes is works for a few seconds   

what can be the problem

**Comment by tomaae** [comment]
if the  setup was successful, that means you were able to connect and integration should work. otherwise it could be something with your network configuration in HA device.
also, check your ha log for any errors

**Comment by lhvandersteen** [comment]
hello thank you for the answer 
i have now it installed trouhg HACS  the addon is installed 
when i enter the ip and the API key is it showing initialize, 
when i put in a wrong api or ip i get a screen where is showing there is someting wrong ,
so it can find the server and the api key but it can not initialize  ,
what can i change to get it working 

thank you

**Comment by tomaae** [comment]
thats an issue on truenas side reporting issue with cpu load and temperature data.
check those graphs in truenas and also its logs. you should be able to find out more.
