### ISSUE TITLE
[Feature] Lock/Unlock status of encrypted Dataset

### ISSUE THREAD

**Issue by fireblade70** [tomaae/homeassistant-truenas#90]
Although attributes show encryption method, is there any method to view if a encrypted dataset is locked or unlocked? If, not will this need to be a feature request?
I use a passphrase encryption because I want to protect against physical theft. However, I have it's shared to running software where I would like HA to alert me if its accidently left locked (i.e after a Truenas roboot).
Regards.

**Comment by tomaae** [comment]
It should be possible to implement, yea.

**Comment by tomaae** [comment]
not possible, encryption_options is not exported via API, despite it being in documentation.

**Comment by fireblade70** [comment]
> not possible, encryption_options is not exported via API, despite it being in documentation.

But in Jul'23 said it was? I wasnt looking to interact with the encryption options. I was looking for the an attribute that would simply show it's status of locked or unlocked. Is this not possible please?
