### ISSUE TITLE
[Bug] Do not show correct sensor names when added to the dashboard.

### ISSUE THREAD

**Issue by Mushishi** [tomaae/homeassistant-truenas#91]
## Describe the issue
If i look at the sensor list of example my disks it do show up with the disk names (nvme* and sd*), but when i add it to the Dashboard it just shows them as FS01 Disks (FS01 is the name of my truenas) and the sensor path to them is sensor.fs01_disks_1,2,3 and not nvme* or sd* like it was before.
It is the same with Datasets and Services list.

## How to reproduce the issue
After i had change my TrueNAS hardware and reinstalled TrueNAS Scale i did remove the old intergration and did readd it it changed to this behavor. The only thing diffrent from this setup was a new install of TrueNAS Scale 22.12.3.2 where the last intergration was form a system that have been upgraded.

## Expected behavior
That it would show the names and not just call them Disks, Services and Datasets in Dashboard. 

## Screenshots
Expected behavor:
![disks_expected](https://github.com/tomaae/homeassistant-truenas/assets/559009/f441c691-ba52-4e15-8e86-f842687475c6)

What it shows when adding and added to the dashboard:
![disks_wrong](https://github.com/tomaae/homeassistant-truenas/assets/559009/76615ff2-2a45-499c-9cf5-5baa26a8246d)

## Software versions

 - Home Assistant version: 2023.7.2
 - TrueNAS integration version: 1.2.3
 - TrueNAS version: Scale 22.12.3.2

## Additional context
This is the code for the Disk card when added to a dashboard:
```
type: entities
entities:
  - sensor.fs01_disks
  - sensor.fs01_disks_2
  - sensor.fs01_disks_3
  - sensor.fs01_disks_4
  - sensor.fs01_disks_5
  - sensor.fs01_disks_6
  - sensor.fs01_disks_7
  - sensor.fs01_disks_8
  - sensor.fs01_disks_9
  - sensor.fs01_disks_10
  - sensor.fs01_disks_11
  - sensor.fs01_disks_12
  - sensor.fs01_disks_13
  - sensor.fs01_disks_14
  - sensor.fs01_disks_15
  - sensor.fs01_disks_16
  - sensor.fs01_disks_17
title: FS01 Disks
```

**Comment by Mushishi** [comment]
Sure will do that. Though i can see that there is a truenas scale update so will apply that first and try to readd the intergration again. Just need to wait till a bit later today when i am not using the shares.

**Comment by Mushishi** [comment]
I hope this is what you need tomaae i had debug enabled when i did add my truenas scale server again after i had upgraded it to 22.12.3.3, and it is the same at this point that it shows the skisk just as disks and services as services.

(I did hide the share names in the log with ****** just for personalation and sharenames do not have the problems with the dashboards)
[truenas_intergration.txt](https://github.com/tomaae/homeassistant-truenas/files/12193299/truenas_intergration.txt)

**Comment by tomaae** [comment]
They seem to be created correctly
```
2023-07-28 13:00:58.487 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-disk-nvme1n1
2023-07-28 13:00:58.487 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-disk-sdb
2023-07-28 13:00:58.487 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-disk-sdc
2023-07-28 13:00:58.488 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-disk-sdf
2023-07-28 13:00:58.488 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-disk-sdd
2023-07-28 13:00:58.488 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-disk-sde
```

Taking example:
```
2023-07-28 13:00:56.248 DEBUG (SyncWorker_11) [custom_components.truenas.apiparser] Processing entry {'identifier': '{serial_lunid}S4D16WWM0000K705DXHD_5000c5009863a85f', 'name': 'sdd', 'subsystem': 'scsi', 'number': 2096, 'serial': '**REDACTED**', 'lunid': '5000c5009863a85f', 'size': 6001175126016, 'description': '', 'transfermode': 'Auto', 'hddstandby': 'ALWAYS ON', 'advpowermgmt': 'DISABLED', 'togglesmart': True, 'smartoptions': '', 'expiretime': None, 'critical': None, 'difference': None, 'informational': None, 'model': 'ST6000NM0034', 'rotationrate': 7200, 'type': 'HDD', 'zfs_guid': '12243305044132658044', 'bus': 'SCSI', 'devname': 'sdd', 'enclosure': None, 'supports_smart': None, 'pool': None}
```
Both devname and name are filled and correct.

Lets check how it looks in ha ui. Click on one of disks and settings. It should show something like this:
![Screenshot 2023-08-02 095537](https://github.com/tomaae/homeassistant-truenas/assets/23486452/805326cf-6ec9-4561-887d-e2ae1f62f80b)
Entity id is what we are looking for. Both one created by integration where is shows correct name and after you add it to dashboard.
Not sure whats going on there, this may be a tough one.

**Comment by Mushishi** [comment]
Not sure what there might be updated while i was on vacation other then i installed the latest HA update but it now show the names correct. So might just be a fluke in my 2023.7.2 where it had nor read the name. 

Now with the latest HA version 2023.8.1 though i can't see any default cards. So one thing was fixed and now another popped up. 

This is what i see looking at the the disk "tab" under the truenas device:
![image](https://github.com/tomaae/homeassistant-truenas/assets/559009/dd474f49-0e0e-4061-8420-fc7f3cf9c980)

But all the entries are still there and they show up with the correct names in the dashboards i had setup already.

![image](https://github.com/tomaae/homeassistant-truenas/assets/559009/653535db-7612-4853-a00b-60d3cb916d3f)

**Comment by tomaae** [comment]
yea, 2023.8 broken links between entities. so you wont see anything in integration card.
have to update integration to fix it.
I will be testing it on several truenas VMs, so we will see if I can replicate your issue

**Comment by Mushishi** [comment]
I will do some testings with a new HA install here this week also to see if is my old install that did it but atleast the name problems is solved.
