### ISSUE TITLE
Configuration of integration fails when unused interfaces do not produce graph data [Bug]

### ISSUE THREAD

**Issue by dbullendsl** [tomaae/homeassistant-truenas#93]
### Configuration of integration fails when unused interfaces do not produce graph data

I have two TrueNAS Core servers on my home network both were working perfectly until I upgraded the mainboard for one of the servers. This board has four NIC's but I'm currently only using one. So there's no data being produced for the other three. Reinstalling the integration for the upgraded server produces the following results in the log:

TrueNAS 10.0.0.48 unable to fetch data "reporting/get_data" (500)
7:37:10 AM – (WARNING) TrueNAS (custom integration) - message first occurred at 7:36:46 AM and shows up 30 times
TrueNAS 10.0.0.48 fetching following graphs failed, check your NAS: ['interface', 'interface', 'interface', 'interface', 'interface', 'interface', 'interface', 'interface', 'interface', 'interface', 'interface']
7:37:09 AM – (WARNING) TrueNAS (custom integration) - message first occurred at 7:36:49 AM and shows up 13 times
TrueNAS 10.0.0.48 fetching following graphs failed, check your NAS: ['interface', 'interface']
7:36:48 AM – (WARNING) TrueNAS (custom integration)

reviewing previous reports here it's suggested that the graph data be reviewed because the problem is with the server. This however doesn't seem to be the solution to this issue as I wouldn't expect to see any data from the 3 unused interfaces.

Is there any way to force the TrueNAS integration to ignore the result when there's no data for the unused devices?

**Comment by tomaae** [comment]
that is only warning during startup, integration should work anyway.
that aside, even unused interfaces produce graph data, I just tested it. you probably have issue wiuth graphing.

**Comment by dbullendsl** [comment]
Further information:
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/truenas/truenas_controller.py:124
Integration: TrueNAS (documentation, issues)
First occurred: August 1, 2023 at 7:43:38 AM (2 occurrences)
Last logged: 7:41:12 AM

Error setting up entry TrueNAS1 for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 124, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
asyncio.exceptions.CancelledError

**Comment by tomaae** [comment]
you have to fix your issue in truenas first.

**Comment by dbullendsl** [comment]
I have no issue, all the graphs are present

**Comment by tomaae** [comment]
even graphs from unused devices should be present. for me it shows 0 all the time for unused device

**Comment by dbullendsl** [comment]
that is what I have, 3 unused/unconfigured interface devices. Each show zero for each of the parameters Rx, Tx, Overlap

**Comment by tomaae** [comment]
can you give me list of all your interfaces with their config and status?
I will try to emulate it in VM

**Comment by dbullendsl** [comment]
Here you go: Thank you
NIC cards are igc0, igc1, igc2, igc3

root@FreeNAS1:~ # ifconfig
igc0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: LAN0
     options=4e527bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether 00:e2:69:6d:63:b8
        inet 10.0.0.48 netmask 0xffffff00 broadcast 10.0.0.255
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=9<PERFORMNUD,IFDISABLED>
igc1: flags=8822<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4e527bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether 00:e2:69:6d:63:b9
        media: Ethernet autoselect
        status: no carrier
        nd6 options=9<PERFORMNUD,IFDISABLED>
igc2: flags=8822<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4e527bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether 00:e2:69:6d:63:ba
        media: Ethernet autoselect
        status: no carrier
        nd6 options=9<PERFORMNUD,IFDISABLED>
igc3: flags=8822<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4e527bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether 00:e2:69:6d:63:bb
        media: Ethernet autoselect
        status: no carrier
        nd6 options=9<PERFORMNUD,IFDISABLED>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

**Comment by dbullendsl** [comment]
Any update?

**Comment by tomaae** [comment]
not yet. I will look into this as part of planned coordinator update. but that will take some time.

**Comment by dbullendsl** [comment]
I've found the solution, totally unrelated to this integration and was a problem with the actual server - 
Please close this Bug Report

**Comment by albertromkes** [comment]
Can you share the solution? I'm running into the same issue.

**Comment by dbullendsl** [comment]
The solution was multi part - first I discovered that I was having problems with the failing server's local SSL certificate. Made many attempts and renewing, replacing, etc.  in the end all failed. Eventually I decided to abandon the attempts at repair and rebuild the entire server with a new install of TrueNAS Core, manually reconfiguring without importing the old configuration. I only use this server as a backup server where I replicate all the shares from my primary (working) NAS. I didn't have to rebuild the ZFS pool and was able to import this existing pool.

Once I had the server rebuilt ( which actually took a lot less time than the time I'd spent trying to get the TrueNAS integrations working). So using the SSL certificate that was installed as part of the new install, I generated a new API key and tried to reconnect to the integration -- and it worked - everything showed up like it was supposed to.

The other issue I had that all the sensors were basically generic,  like sensor.boot_pool_free I fixed by manually editing the file /config/.storage/core.entity_registry., so that now my sensors are like sensor.servername_boot_pool_free. There were some 110 entities for one server and 98 for the other .  If you decide to do this - USE EXTREME CAUTION - if you goof up you'll really screw things up and you may have to re-install everything or at the minimum restore a backup from a working
