### ISSUE TITLE
[Bug] Space used does not update

### ISSUE THREAD

**Issue by anto294** [tomaae/homeassistant-truenas#94]
Hello,
the sensor of space used "sensor.truenas_datasets_poolx", does not update automatically. You need to reload the integration.

Theoretically it should update every minute

**Comment by tomaae** [comment]
check your HA log for errors

**Comment by anto294** [comment]
Unfortunately, no error or warning appears in the logs. Otherwise I would have reported it

**Comment by tomaae** [comment]
Ok, run it in debug to see if it is actually running query every minute.
Also, what is your truenas version?

**Comment by anto294** [comment]
The only one error is:
`Ignoring invalid device info: Invalid device info {'configuration_url': 'http://192.168.178.103', 'connections': {('truenas', 'truenas')}, 'default_manufacturer': 'To Be Filled By O.E.M.', 'default_model': 'B550M PG Riptide', 'default_name': 'TrueNAS System', 'identifiers': {('truenas', 'truenas')}, 'sw_version': 'TrueNAS-SCALE-22.12.3.3', 'via_device': ('truenas', 'truenas')} for 'truenas' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

TrueNAS 22.12.3.3
I use this integration since November 2022, but it's always been doing that.

**Comment by tomaae** [comment]
that error is related to 2023.8. it will affect only entities not showing up in integrations under device. otherwise they will be available.

Always? Strange that nobody noticed that yet.
Is it affecting just dataset sensors, or also pool sensors in "System" section?

**Comment by jmnovak50** [comment]
Hi @tomaae,

I’m seeing similar behavior on my install.  Seems that pools are refreshing but datasets are not…unless I reload the integration.

**Comment by jmnovak50** [comment]
More on this…also ran in debug…

Logger: homeassistant.components.update
Source: helpers/entity_platform.py:624 
Integration: Update (documentation, issues) 
First occurred: August 7, 2023 at 10:49:45 PM (2 occurrences) 
Last logged: 8:33:25 PM

Ignoring invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.xxx, 'connections': {('truenas', 'habanero')}, 'default_manufacturer': 'ASUS', 'default_model': 'System Product Name', 'default_name': 'TrueNAS System', 'identifiers': {('truenas', 'habanero')}, 'sw_version': 'TrueNAS-SCALE-22.12.3.3', 'via_device': ('truenas', 'habanero')} for 'truenas' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by anto294** [comment]
> that error is related to 2023.8. it will affect only entities not showing up in integrations under device. otherwise they will be available.
> 
> Always? Strange that nobody noticed that yet. Is it affecting just dataset sensors, or also pool sensors in "System" section?

Only dataset. 
I didn't report this bug first because of my lack 😅. Now I want to create a % used space sensor, and I need updated value.

**Comment by tomaae** [comment]
ok, thats a weird one. I think I see same issue with my install, just didnt noticed it. I was using pool info until now which works.

**Comment by tomaae** [comment]
I have been trying to debug this with cleanup of one dataset, went from 17.57 to 9.
Dataset size didnt changed, zfs list was reporting used as 17.57 and 9 as reffered. This is due to scheduled snapshots. I deleted them and used went to 9.

Can you check on your side?

**Comment by anto294** [comment]
Unfortunately, I have the new version Cobia 23.10-Beta1. R.C. is coming out tomorrow.
As you already know, the integration is not compatible yet.

I assure you that the sensor did not decrease even by deleting zfs snapshots.
It didn't even increase if I copied files for over a TB.

**Comment by tomaae** [comment]
can you test using `zfs list|grep <dataset you used>` and also look in UI if value changed?

**Comment by anto294** [comment]
Of course!

Initial:
![Screenshot 2023-09-18 105312](https://github.com/tomaae/homeassistant-truenas/assets/10341813/b9e63c01-2678-406c-8828-d1f024ad92d2)

+379GB on tank/Temp
![Screenshot 2023-09-18 111521](https://github.com/tomaae/homeassistant-truenas/assets/10341813/a3e94e10-51f0-4808-9517-72de9f4b5e63)

File deleted, but present on ZFS snapshot:
![Screenshot 2023-09-18 111849](https://github.com/tomaae/homeassistant-truenas/assets/10341813/9fa10cc6-
![Screenshot 2023-09-18 112018](https://github.com/tomaae/homeassistant-truenas/assets/10341813/d2e61070-83df-471d-90cd-e9c5b2cc7a94)
04d2-4aa7-970a-04c847292d11)

After removed snapshot:
![Screenshot 2023-09-18 112107](https://github.com/tomaae/homeassistant-truenas/assets/10341813/9fb6fa24-8409-4ea5-a57f-4b0fd9f73973)

**Comment by tomaae** [comment]
yup, same behavior. but it should be like this. I think this was the root cause

**Comment by tomaae** [comment]
![image](https://github.com/tomaae/homeassistant-truenas/assets/23486452/656c7549-4023-4218-b9a4-995e30e7423b)
can confirm its working fine in master
