### ISSUE TITLE
[Bug] Temperatures shown as Fahrenheit instead of Celsius.

### ISSUE THREAD

**Issue by ReenigneArcher** [tomaae/homeassistant-truenas#96]
## Describe the issue

All temps shown as degrees F. Should be degrees C.

## How to reproduce the issue

Install and setup integration.

## Expected behavior

Integration sets correct unit of measure.

## Screenshots

![Screenshot_20230808-083506.png](https://github.com/tomaae/homeassistant-truenas/assets/42013603/f5c20f55-a160-4835-805a-d1cdce570561)

## Software versions

 - Home Assistant version: 
 - TrueNAS integration version: 
 - TrueNAS version: 
HA 2023.7.3
Integration v1.2.3
TrueNAS scale 22.02.4

**Comment by tomaae** [comment]
yes, I'm aware of that. this integration is not yet reworked to newest parameter system.

**Comment by tomaae** [comment]
Fixed in 13dba2a5725f579a8929d15fe241f8cc8290d7fb
