### ISSUE TITLE
Set Area for TrueNAS entities[Question]

### ISSUE THREAD

**Issue by fireblade70** [tomaae/homeassistant-truenas#99]
How do you set an Area for all the Truenas entities in batch? Before recent updates I had Device for each device type i.e Dataset, Snapshot etc etc. Now I have no devices, just 99 entities (all software upto date)

**Comment by tomaae** [comment]
truenas does not have self managed areas, you use standard HA methods as with everything else.
Devices are missing because of undocumented breaking change in last HA release which affects connection between devices. this is mostly cosmetic issue and does not affect functionality.
